# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I_DlogJC_2Dcode.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Class_DlogJC_2Dcode(object):
    def setupUi(self, Class_DlogJC_2Dcode):
        Class_DlogJC_2Dcode.setObjectName("Class_DlogJC_2Dcode")
        Class_DlogJC_2Dcode.resize(452, 979)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Class_DlogJC_2Dcode)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget_2 = QtWidgets.QWidget(Class_DlogJC_2Dcode)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalWidget_2.setStyleSheet("background-color: rgb(32, 74, 135);")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label.setStyleSheet("color: rgb(238, 238, 236);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.horizontalWidget_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Class_DlogJC_2Dcode)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -359, 432, 1202))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(400, 1200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalFrame_8 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_8.setMinimumSize(QtCore.QSize(0, 50))
        self.verticalFrame_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalFrame_8.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.verticalFrame_8.setObjectName("verticalFrame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalFrame_8)
        self.verticalLayout_11.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.verticalLayout_9.addWidget(self.verticalFrame_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 258))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(20, 5, -1, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_4.addWidget(self.label_22)
        self.cbox_Single_JC_2Dcode = QtWidgets.QCheckBox(self.frame_2)
        self.cbox_Single_JC_2Dcode.setObjectName("cbox_Single_JC_2Dcode")
        self.horizontalLayout_4.addWidget(self.cbox_Single_JC_2Dcode)
        self.cbox_Multiple_JC_2Dcode = QtWidgets.QCheckBox(self.frame_2)
        self.cbox_Multiple_JC_2Dcode.setObjectName("cbox_Multiple_JC_2Dcode")
        self.horizontalLayout_4.addWidget(self.cbox_Multiple_JC_2Dcode)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 10, 10, 10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.btn_ConditionsList_JC_2Dcode = QtWidgets.QPushButton(self.frame_2)
        self.btn_ConditionsList_JC_2Dcode.setObjectName("btn_ConditionsList_JC_2Dcode")
        self.horizontalLayout_13.addWidget(self.btn_ConditionsList_JC_2Dcode)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(30, 5, 10, 5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_15.addWidget(self.label_2)
        self.combox_DataRange_JC_2Dcode = QtWidgets.QComboBox(self.frame_2)
        self.combox_DataRange_JC_2Dcode.setObjectName("combox_DataRange_JC_2Dcode")
        self.combox_DataRange_JC_2Dcode.addItem("")
        self.combox_DataRange_JC_2Dcode.addItem("")
        self.combox_DataRange_JC_2Dcode.addItem("")
        self.combox_DataRange_JC_2Dcode.addItem("")
        self.combox_DataRange_JC_2Dcode.addItem("")
        self.combox_DataRange_JC_2Dcode.addItem("")
        self.combox_DataRange_JC_2Dcode.addItem("")
        self.combox_DataRange_JC_2Dcode.addItem("")
        self.combox_DataRange_JC_2Dcode.addItem("")
        self.horizontalLayout_15.addWidget(self.combox_DataRange_JC_2Dcode)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.horizontalFrame_8 = QtWidgets.QFrame(self.frame_2)
        self.horizontalFrame_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalFrame_8.setObjectName("horizontalFrame_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalFrame_8)
        self.horizontalLayout_14.setContentsMargins(20, 0, 10, 0)
        self.horizontalLayout_14.setSpacing(15)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.horizontalFrame_8)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.lab_StartDigit_JC_2Dcode = QtWidgets.QLabel(self.horizontalFrame_8)
        self.lab_StartDigit_JC_2Dcode.setMinimumSize(QtCore.QSize(20, 0))
        self.lab_StartDigit_JC_2Dcode.setObjectName("lab_StartDigit_JC_2Dcode")
        self.horizontalLayout_14.addWidget(self.lab_StartDigit_JC_2Dcode)
        self.label_14 = QtWidgets.QLabel(self.horizontalFrame_8)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.lab_EndDigit_JC_2Dcode = QtWidgets.QLabel(self.horizontalFrame_8)
        self.lab_EndDigit_JC_2Dcode.setMinimumSize(QtCore.QSize(40, 0))
        self.lab_EndDigit_JC_2Dcode.setObjectName("lab_EndDigit_JC_2Dcode")
        self.horizontalLayout_14.addWidget(self.lab_EndDigit_JC_2Dcode)
        self.verticalLayout_13.addWidget(self.horizontalFrame_8)
        self.asdasd = QtWidgets.QFrame(self.frame_2)
        self.asdasd.setMinimumSize(QtCore.QSize(0, 30))
        self.asdasd.setMaximumSize(QtCore.QSize(16777215, 40))
        self.asdasd.setObjectName("asdasd")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.asdasd)
        self.horizontalLayout_12.setContentsMargins(20, 0, -1, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_16 = QtWidgets.QLabel(self.asdasd)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.verticalLayout_13.addWidget(self.asdasd)
        self.horizontalFrame_6 = QtWidgets.QFrame(self.frame_2)
        self.horizontalFrame_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_11.setContentsMargins(40, 5, 10, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lab_ReadData_JC_2Dcode = QtWidgets.QLabel(self.horizontalFrame_6)
        self.lab_ReadData_JC_2Dcode.setMinimumSize(QtCore.QSize(80, 30))
        self.lab_ReadData_JC_2Dcode.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lab_ReadData_JC_2Dcode.setFrameShape(QtWidgets.QFrame.Box)
        self.lab_ReadData_JC_2Dcode.setText("")
        self.lab_ReadData_JC_2Dcode.setObjectName("lab_ReadData_JC_2Dcode")
        self.horizontalLayout_11.addWidget(self.lab_ReadData_JC_2Dcode)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.btn_ReadData_JC_2Dcode = QtWidgets.QPushButton(self.horizontalFrame_6)
        self.btn_ReadData_JC_2Dcode.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_ReadData_JC_2Dcode.setObjectName("btn_ReadData_JC_2Dcode")
        self.horizontalLayout_11.addWidget(self.btn_ReadData_JC_2Dcode)
        self.verticalLayout_13.addWidget(self.horizontalFrame_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(20, 5, 10, 5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.btn_CopyReadData_JC_2Dcode = QtWidgets.QPushButton(self.frame_2)
        self.btn_CopyReadData_JC_2Dcode.setObjectName("btn_CopyReadData_JC_2Dcode")
        self.horizontalLayout_10.addWidget(self.btn_CopyReadData_JC_2Dcode)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.ooip = QtWidgets.QFrame(self.frame_2)
        self.ooip.setMinimumSize(QtCore.QSize(0, 40))
        self.ooip.setObjectName("ooip")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.ooip)
        self.horizontalLayout_9.setContentsMargins(30, 0, 10, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tedit_CopyReadData_JC_2Dcode = QtWidgets.QTextEdit(self.ooip)
        self.tedit_CopyReadData_JC_2Dcode.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tedit_CopyReadData_JC_2Dcode.setObjectName("tedit_CopyReadData_JC_2Dcode")
        self.horizontalLayout_9.addWidget(self.tedit_CopyReadData_JC_2Dcode)
        self.verticalLayout_13.addWidget(self.ooip)
        self.eee = QtWidgets.QFrame(self.frame_2)
        self.eee.setStyleSheet("color: rgb(0, 0, 0);")
        self.eee.setObjectName("eee")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.eee)
        self.horizontalLayout_17.setContentsMargins(20, 0, 10, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_20 = QtWidgets.QLabel(self.eee)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.btn_ConversionSetting_JC_2Dcode = QtWidgets.QPushButton(self.eee)
        self.btn_ConversionSetting_JC_2Dcode.setObjectName("btn_ConversionSetting_JC_2Dcode")
        self.horizontalLayout_17.addWidget(self.btn_ConversionSetting_JC_2Dcode)
        self.verticalLayout_13.addWidget(self.eee)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(30, 5, 10, 5)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lab_Coverted_JC_2Dcode = QtWidgets.QLabel(self.frame_2)
        self.lab_Coverted_JC_2Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.lab_Coverted_JC_2Dcode.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lab_Coverted_JC_2Dcode.setFrameShape(QtWidgets.QFrame.Box)
        self.lab_Coverted_JC_2Dcode.setText("")
        self.lab_Coverted_JC_2Dcode.setObjectName("lab_Coverted_JC_2Dcode")
        self.horizontalLayout_8.addWidget(self.lab_Coverted_JC_2Dcode)
        self.btn_ConvertedDetail_JC_2Dcode = QtWidgets.QPushButton(self.frame_2)
        self.btn_ConvertedDetail_JC_2Dcode.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_ConvertedDetail_JC_2Dcode.setObjectName("btn_ConvertedDetail_JC_2Dcode")
        self.horizontalLayout_8.addWidget(self.btn_ConvertedDetail_JC_2Dcode)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.verticalFrame_81 = QtWidgets.QFrame(self.frame_2)
        self.verticalFrame_81.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalFrame_81.setObjectName("verticalFrame_81")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.verticalFrame_81)
        self.horizontalLayout_16.setContentsMargins(20, 0, 10, 0)
        self.horizontalLayout_16.setSpacing(60)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.verticalFrame_81)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_16.addWidget(self.label_7)
        self.verticalLayout_13.addWidget(self.verticalFrame_81)
        self.horizontalFrame = QtWidgets.QFrame(self.frame_2)
        self.horizontalFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_3.setContentsMargins(30, 5, 10, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lab_CollationResult_JC_2Dcode = QtWidgets.QLabel(self.horizontalFrame)
        self.lab_CollationResult_JC_2Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.lab_CollationResult_JC_2Dcode.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lab_CollationResult_JC_2Dcode.setFrameShape(QtWidgets.QFrame.Box)
        self.lab_CollationResult_JC_2Dcode.setText("")
        self.lab_CollationResult_JC_2Dcode.setObjectName("lab_CollationResult_JC_2Dcode")
        self.horizontalLayout_3.addWidget(self.lab_CollationResult_JC_2Dcode)
        self.verticalLayout_13.addWidget(self.horizontalFrame)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalFrame_82 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_82.setMinimumSize(QtCore.QSize(0, 50))
        self.verticalFrame_82.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalFrame_82.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.verticalFrame_82.setObjectName("verticalFrame_82")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalFrame_82)
        self.verticalLayout_14.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.verticalFrame_82)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.verticalLayout_8.addWidget(self.verticalFrame_82)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalFrame_11 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_11.setMaximumSize(QtCore.QSize(16777215, 40))
        self.verticalFrame_11.setObjectName("verticalFrame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.verticalFrame_11)
        self.horizontalLayout_6.setContentsMargins(20, 0, 10, 0)
        self.horizontalLayout_6.setSpacing(30)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.verticalFrame_11)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.tedit_UpperLimit_Length_JC_2Dcode = QtWidgets.QTextEdit(self.verticalFrame_11)
        self.tedit_UpperLimit_Length_JC_2Dcode.setMinimumSize(QtCore.QSize(180, 30))
        self.tedit_UpperLimit_Length_JC_2Dcode.setMaximumSize(QtCore.QSize(180, 30))
        self.tedit_UpperLimit_Length_JC_2Dcode.setObjectName("tedit_UpperLimit_Length_JC_2Dcode")
        self.horizontalLayout_6.addWidget(self.tedit_UpperLimit_Length_JC_2Dcode)
        self.verticalLayout_12.addWidget(self.verticalFrame_11)
        self.cczczxczx = QtWidgets.QFrame(self.frame)
        self.cczczxczx.setMinimumSize(QtCore.QSize(0, 40))
        self.cczczxczx.setMaximumSize(QtCore.QSize(16777215, 40))
        self.cczczxczx.setObjectName("cczczxczx")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.cczczxczx)
        self.horizontalLayout_7.setContentsMargins(20, 0, 10, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.cczczxczx)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.tedit_Measured_Length_JC_2Dcode = QtWidgets.QTextEdit(self.cczczxczx)
        self.tedit_Measured_Length_JC_2Dcode.setMaximumSize(QtCore.QSize(180, 30))
        self.tedit_Measured_Length_JC_2Dcode.setObjectName("tedit_Measured_Length_JC_2Dcode")
        self.horizontalLayout_7.addWidget(self.tedit_Measured_Length_JC_2Dcode)
        self.verticalLayout_12.addWidget(self.cczczxczx)
        self.verticalFrame_83 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_83.setMaximumSize(QtCore.QSize(16777215, 40))
        self.verticalFrame_83.setObjectName("verticalFrame_83")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.verticalFrame_83)
        self.horizontalLayout_18.setContentsMargins(20, 0, 10, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_6 = QtWidgets.QLabel(self.verticalFrame_83)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_18.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.tedit_LowerLimit_Length_JC_2Dcode = QtWidgets.QTextEdit(self.verticalFrame_83)
        self.tedit_LowerLimit_Length_JC_2Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.tedit_LowerLimit_Length_JC_2Dcode.setMaximumSize(QtCore.QSize(180, 30))
        self.tedit_LowerLimit_Length_JC_2Dcode.setObjectName("tedit_LowerLimit_Length_JC_2Dcode")
        self.horizontalLayout_18.addWidget(self.tedit_LowerLimit_Length_JC_2Dcode)
        self.verticalLayout_12.addWidget(self.verticalFrame_83)
        self.verticalLayout_8.addLayout(self.verticalLayout_12)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalFrame_4 = QtWidgets.QFrame(self.frame_3)
        self.verticalFrame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.verticalFrame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalFrame_4.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_18.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_24 = QtWidgets.QLabel(self.verticalFrame_4)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_18.addWidget(self.label_24)
        self.verticalLayout_16.addWidget(self.verticalFrame_4)
        self.position = QtWidgets.QFrame(self.frame_3)
        self.position.setMinimumSize(QtCore.QSize(0, 200))
        self.position.setObjectName("position")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.position)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalFrame_4 = QtWidgets.QFrame(self.position)
        self.horizontalFrame_4.setMinimumSize(QtCore.QSize(40, 160))
        self.horizontalFrame_4.setMaximumSize(QtCore.QSize(16777215, 160))
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.horizontalLayout_20.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_20.setSpacing(30)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalFrame = QtWidgets.QFrame(self.horizontalFrame_4)
        self.verticalFrame.setMinimumSize(QtCore.QSize(0, 120))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_21.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_13 = QtWidgets.QLabel(self.verticalFrame)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_21.addWidget(self.label_13)
        self.label_3 = QtWidgets.QLabel(self.verticalFrame)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_21.addWidget(self.label_3)
        self.label_10 = QtWidgets.QLabel(self.verticalFrame)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_21.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.verticalFrame)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_21.addWidget(self.label_12)
        self.horizontalLayout_20.addWidget(self.verticalFrame)
        self.verticalFrame_2 = QtWidgets.QFrame(self.horizontalFrame_4)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_23 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_23.setObjectName("label_23")
        self.verticalLayout_22.addWidget(self.label_23)
        self.tedit_UpperLimit_PosX_JC_2Dcode = QtWidgets.QTextEdit(self.verticalFrame_2)
        self.tedit_UpperLimit_PosX_JC_2Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.tedit_UpperLimit_PosX_JC_2Dcode.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tedit_UpperLimit_PosX_JC_2Dcode.setObjectName("tedit_UpperLimit_PosX_JC_2Dcode")
        self.verticalLayout_22.addWidget(self.tedit_UpperLimit_PosX_JC_2Dcode)
        self.tedit_Measured_PosX_JC_2Dcode = QtWidgets.QTextEdit(self.verticalFrame_2)
        self.tedit_Measured_PosX_JC_2Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.tedit_Measured_PosX_JC_2Dcode.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tedit_Measured_PosX_JC_2Dcode.setObjectName("tedit_Measured_PosX_JC_2Dcode")
        self.verticalLayout_22.addWidget(self.tedit_Measured_PosX_JC_2Dcode)
        self.tedit_LowerLimit_PosX_JC_2Dcode_2 = QtWidgets.QTextEdit(self.verticalFrame_2)
        self.tedit_LowerLimit_PosX_JC_2Dcode_2.setMinimumSize(QtCore.QSize(0, 30))
        self.tedit_LowerLimit_PosX_JC_2Dcode_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tedit_LowerLimit_PosX_JC_2Dcode_2.setObjectName("tedit_LowerLimit_PosX_JC_2Dcode_2")
        self.verticalLayout_22.addWidget(self.tedit_LowerLimit_PosX_JC_2Dcode_2)
        self.horizontalLayout_20.addWidget(self.verticalFrame_2)
        self.verticalFrame_3 = QtWidgets.QFrame(self.horizontalFrame_4)
        self.verticalFrame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_25 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_25.setObjectName("label_25")
        self.verticalLayout_23.addWidget(self.label_25)
        self.tedit_UpperLimit_PosY_JC_2Dcode = QtWidgets.QTextEdit(self.verticalFrame_3)
        self.tedit_UpperLimit_PosY_JC_2Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.tedit_UpperLimit_PosY_JC_2Dcode.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tedit_UpperLimit_PosY_JC_2Dcode.setObjectName("tedit_UpperLimit_PosY_JC_2Dcode")
        self.verticalLayout_23.addWidget(self.tedit_UpperLimit_PosY_JC_2Dcode)
        self.tedit_Measured_PosY_JC_2Dcode = QtWidgets.QTextEdit(self.verticalFrame_3)
        self.tedit_Measured_PosY_JC_2Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.tedit_Measured_PosY_JC_2Dcode.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tedit_Measured_PosY_JC_2Dcode.setObjectName("tedit_Measured_PosY_JC_2Dcode")
        self.verticalLayout_23.addWidget(self.tedit_Measured_PosY_JC_2Dcode)
        self.tedit_LowerLimit_PosY_JC_2Dcode = QtWidgets.QTextEdit(self.verticalFrame_3)
        self.tedit_LowerLimit_PosY_JC_2Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.tedit_LowerLimit_PosY_JC_2Dcode.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tedit_LowerLimit_PosY_JC_2Dcode.setObjectName("tedit_LowerLimit_PosY_JC_2Dcode")
        self.verticalLayout_23.addWidget(self.tedit_LowerLimit_PosY_JC_2Dcode)
        self.horizontalLayout_20.addWidget(self.verticalFrame_3)
        self.verticalLayout_19.addWidget(self.horizontalFrame_4)
        self.verticalLayout_16.addWidget(self.position)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.verticalLayout_10.addWidget(self.frame_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_10)
        self.angle = QtWidgets.QFrame(self.frame)
        self.angle.setMinimumSize(QtCore.QSize(0, 120))
        self.angle.setObjectName("angle")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.angle)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalFrame1 = QtWidgets.QFrame(self.angle)
        self.horizontalFrame1.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalFrame1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame1.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.horizontalFrame1.setObjectName("horizontalFrame1")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalFrame1)
        self.horizontalLayout_21.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_15 = QtWidgets.QLabel(self.horizontalFrame1)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_21.addWidget(self.label_15)
        self.verticalLayout_15.addWidget(self.horizontalFrame1)
        self.verticalFrame1 = QtWidgets.QFrame(self.angle)
        self.verticalFrame1.setMinimumSize(QtCore.QSize(0, 150))
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.verticalFrame1)
        self.horizontalFrame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_23.setContentsMargins(20, 0, 10, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_18 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem6)
        self.tedit_UpperLimit_Angle_JC_2Dcode = QtWidgets.QTextEdit(self.horizontalFrame_2)
        self.tedit_UpperLimit_Angle_JC_2Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.tedit_UpperLimit_Angle_JC_2Dcode.setMaximumSize(QtCore.QSize(150, 30))
        self.tedit_UpperLimit_Angle_JC_2Dcode.setObjectName("tedit_UpperLimit_Angle_JC_2Dcode")
        self.horizontalLayout_23.addWidget(self.tedit_UpperLimit_Angle_JC_2Dcode)
        self.verticalLayout_20.addWidget(self.horizontalFrame_2)
        self.verticalWidget = QtWidgets.QWidget(self.verticalFrame1)
        self.verticalWidget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.verticalWidget.setObjectName("verticalWidget")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.verticalWidget)
        self.horizontalLayout_25.setContentsMargins(20, 0, 10, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_19 = QtWidgets.QLabel(self.verticalWidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_25.addWidget(self.label_19)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem7)
        self.tedit_Measured_Angle_JC_2Dcode = QtWidgets.QTextEdit(self.verticalWidget)
        self.tedit_Measured_Angle_JC_2Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.tedit_Measured_Angle_JC_2Dcode.setMaximumSize(QtCore.QSize(150, 30))
        self.tedit_Measured_Angle_JC_2Dcode.setObjectName("tedit_Measured_Angle_JC_2Dcode")
        self.horizontalLayout_25.addWidget(self.tedit_Measured_Angle_JC_2Dcode)
        self.verticalLayout_20.addWidget(self.verticalWidget)
        self.horizontalFrame2 = QtWidgets.QFrame(self.verticalFrame1)
        self.horizontalFrame2.setMinimumSize(QtCore.QSize(0, 40))
        self.horizontalFrame2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalFrame2.setObjectName("horizontalFrame2")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalFrame2)
        self.horizontalLayout_22.setContentsMargins(20, 0, 10, 0)
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtWidgets.QLabel(self.horizontalFrame2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem8)
        self.tedit_LowerLimit_Angle_JC_2Dcode = QtWidgets.QTextEdit(self.horizontalFrame2)
        self.tedit_LowerLimit_Angle_JC_2Dcode.setMinimumSize(QtCore.QSize(30, 0))
        self.tedit_LowerLimit_Angle_JC_2Dcode.setMaximumSize(QtCore.QSize(150, 30))
        self.tedit_LowerLimit_Angle_JC_2Dcode.setObjectName("tedit_LowerLimit_Angle_JC_2Dcode")
        self.horizontalLayout_22.addWidget(self.tedit_LowerLimit_Angle_JC_2Dcode)
        self.verticalLayout_20.addWidget(self.horizontalFrame2)
        self.verticalLayout_15.addWidget(self.verticalFrame1)
        self.verticalLayout_6.addWidget(self.angle)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addWidget(self.frame)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalFrame3 = QtWidgets.QFrame(Class_DlogJC_2Dcode)
        self.horizontalFrame3.setMinimumSize(QtCore.QSize(0, 80))
        self.horizontalFrame3.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.horizontalFrame3.setObjectName("horizontalFrame3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame3)
        self.horizontalLayout.setContentsMargins(10, 0, 10, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.btn_OK_JC_2Dcode = QtWidgets.QPushButton(self.horizontalFrame3)
        self.btn_OK_JC_2Dcode.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_OK_JC_2Dcode.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_OK_JC_2Dcode.setObjectName("btn_OK_JC_2Dcode")
        self.horizontalLayout.addWidget(self.btn_OK_JC_2Dcode)
        self.btn_Cancel_JC_2Dcode = QtWidgets.QPushButton(self.horizontalFrame3)
        self.btn_Cancel_JC_2Dcode.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_Cancel_JC_2Dcode.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(238, 238, 236);")
        self.btn_Cancel_JC_2Dcode.setObjectName("btn_Cancel_JC_2Dcode")
        self.horizontalLayout.addWidget(self.btn_Cancel_JC_2Dcode)
        self.verticalLayout.addWidget(self.horizontalFrame3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Class_DlogJC_2Dcode)
        QtCore.QMetaObject.connectSlotsByName(Class_DlogJC_2Dcode)

    def retranslateUi(self, Class_DlogJC_2Dcode):
        _translate = QtCore.QCoreApplication.translate
        Class_DlogJC_2Dcode.setWindowTitle(_translate("Class_DlogJC_2Dcode", "Dialog"))
        self.label.setText(_translate("Class_DlogJC_2Dcode", "2D Code Reader   > Judgment Conditions"))
        self.label_4.setText(_translate("Class_DlogJC_2Dcode", "Data Collation"))
        self.label_22.setText(_translate("Class_DlogJC_2Dcode", "Condition"))
        self.cbox_Single_JC_2Dcode.setText(_translate("Class_DlogJC_2Dcode", "Single"))
        self.cbox_Multiple_JC_2Dcode.setText(_translate("Class_DlogJC_2Dcode", "Multiple"))
        self.btn_ConditionsList_JC_2Dcode.setText(_translate("Class_DlogJC_2Dcode", "Condition List"))
        self.label_2.setText(_translate("Class_DlogJC_2Dcode", "Data Range"))
        self.combox_DataRange_JC_2Dcode.setItemText(0, _translate("Class_DlogJC_2Dcode", "All Data"))
        self.combox_DataRange_JC_2Dcode.setItemText(1, _translate("Class_DlogJC_2Dcode", "Split 1"))
        self.combox_DataRange_JC_2Dcode.setItemText(2, _translate("Class_DlogJC_2Dcode", "Split 2"))
        self.combox_DataRange_JC_2Dcode.setItemText(3, _translate("Class_DlogJC_2Dcode", "Split 3"))
        self.combox_DataRange_JC_2Dcode.setItemText(4, _translate("Class_DlogJC_2Dcode", "Split 4"))
        self.combox_DataRange_JC_2Dcode.setItemText(5, _translate("Class_DlogJC_2Dcode", "Split 5"))
        self.combox_DataRange_JC_2Dcode.setItemText(6, _translate("Class_DlogJC_2Dcode", "Split 6"))
        self.combox_DataRange_JC_2Dcode.setItemText(7, _translate("Class_DlogJC_2Dcode", "Split 7"))
        self.combox_DataRange_JC_2Dcode.setItemText(8, _translate("Class_DlogJC_2Dcode", "Split 8"))
        self.label_5.setText(_translate("Class_DlogJC_2Dcode", "Start Digit"))
        self.lab_StartDigit_JC_2Dcode.setText(_translate("Class_DlogJC_2Dcode", "<html><head/><body><p align=\"center\">1</p></body></html>"))
        self.label_14.setText(_translate("Class_DlogJC_2Dcode", "Range"))
        self.lab_EndDigit_JC_2Dcode.setText(_translate("Class_DlogJC_2Dcode", "<html><head/><body><p align=\"center\">100</p></body></html>"))
        self.label_16.setText(_translate("Class_DlogJC_2Dcode", "Read Data"))
        self.btn_ReadData_JC_2Dcode.setText(_translate("Class_DlogJC_2Dcode", ">>>"))
        self.label_17.setText(_translate("Class_DlogJC_2Dcode", "Reference Pattern"))
        self.btn_CopyReadData_JC_2Dcode.setText(_translate("Class_DlogJC_2Dcode", "Copy from Read Data"))
        self.label_20.setText(_translate("Class_DlogJC_2Dcode", "(Converted)"))
        self.btn_ConversionSetting_JC_2Dcode.setText(_translate("Class_DlogJC_2Dcode", "Conversion Settings"))
        self.btn_ConvertedDetail_JC_2Dcode.setText(_translate("Class_DlogJC_2Dcode", ">>>"))
        self.label_7.setText(_translate("Class_DlogJC_2Dcode", "Collation  Result"))
        self.label_8.setText(_translate("Class_DlogJC_2Dcode", "Read Data Length"))
        self.label_9.setText(_translate("Class_DlogJC_2Dcode", "Upper Limit"))
        self.label_11.setText(_translate("Class_DlogJC_2Dcode", "Measured  "))
        self.label_6.setText(_translate("Class_DlogJC_2Dcode", "Lower Limit"))
        self.label_24.setText(_translate("Class_DlogJC_2Dcode", "Position"))
        self.label_3.setText(_translate("Class_DlogJC_2Dcode", "Upper Limit"))
        self.label_10.setText(_translate("Class_DlogJC_2Dcode", "Measured  "))
        self.label_12.setText(_translate("Class_DlogJC_2Dcode", "Low Limit"))
        self.label_23.setText(_translate("Class_DlogJC_2Dcode", "Position X"))
        self.label_25.setText(_translate("Class_DlogJC_2Dcode", "Position Y"))
        self.label_15.setText(_translate("Class_DlogJC_2Dcode", "Detected Angle"))
        self.label_18.setText(_translate("Class_DlogJC_2Dcode", "Upper Limit"))
        self.label_19.setText(_translate("Class_DlogJC_2Dcode", "Measured  "))
        self.label_21.setText(_translate("Class_DlogJC_2Dcode", "Low Limit"))
        self.btn_OK_JC_2Dcode.setText(_translate("Class_DlogJC_2Dcode", "OK"))
        self.btn_Cancel_JC_2Dcode.setText(_translate("Class_DlogJC_2Dcode", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Class_DlogJC_2Dcode = QtWidgets.QDialog()
    ui = Ui_Class_DlogJC_2Dcode()
    ui.setupUi(Class_DlogJC_2Dcode)
    Class_DlogJC_2Dcode.show()
    sys.exit(app.exec_())

