# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I_DlogER_2Dcode.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Class_DlogER_2Dcode(object):
    def setupUi(self, Class_DlogER_2Dcode):
        Class_DlogER_2Dcode.setObjectName("Class_DlogER_2Dcode")
        Class_DlogER_2Dcode.resize(452, 482)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Class_DlogER_2Dcode)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(Class_DlogER_2Dcode)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(Class_DlogER_2Dcode)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(Class_DlogER_2Dcode)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(Class_DlogER_2Dcode)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Class_DlogER_2Dcode)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalFrame_5 = QtWidgets.QFrame(Class_DlogER_2Dcode)
        self.verticalFrame_5.setObjectName("verticalFrame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout.addWidget(self.verticalFrame_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(Class_DlogER_2Dcode)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.comBox_InspectionRegion_2Dcode = QtWidgets.QComboBox(Class_DlogER_2Dcode)
        self.comBox_InspectionRegion_2Dcode.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.comBox_InspectionRegion_2Dcode.setObjectName("comBox_InspectionRegion_2Dcode")
        self.comBox_InspectionRegion_2Dcode.addItem("")
        self.horizontalLayout_3.addWidget(self.comBox_InspectionRegion_2Dcode)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(Class_DlogER_2Dcode)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.btn_referencImage_2Dcode = QtWidgets.QPushButton(Class_DlogER_2Dcode)
        self.btn_referencImage_2Dcode.setStyleSheet("\n"
"background-color: rgb(211, 215, 207);")
        self.btn_referencImage_2Dcode.setObjectName("btn_referencImage_2Dcode")
        self.horizontalLayout.addWidget(self.btn_referencImage_2Dcode)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.horizontalFrame_2 = QtWidgets.QFrame(Class_DlogER_2Dcode)
        self.horizontalFrame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.horizontalFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_OK_editRegion_2Dcode = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.btn_OK_editRegion_2Dcode.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);")
        self.btn_OK_editRegion_2Dcode.setObjectName("btn_OK_editRegion_2Dcode")
        self.horizontalLayout_2.addWidget(self.btn_OK_editRegion_2Dcode)
        self.btn_Cancel_editRegion_2Dcode = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.btn_Cancel_editRegion_2Dcode.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(238, 238, 236);")
        self.btn_Cancel_editRegion_2Dcode.setObjectName("btn_Cancel_editRegion_2Dcode")
        self.horizontalLayout_2.addWidget(self.btn_Cancel_editRegion_2Dcode)
        self.verticalLayout.addWidget(self.horizontalFrame_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Class_DlogER_2Dcode)
        QtCore.QMetaObject.connectSlotsByName(Class_DlogER_2Dcode)

    def retranslateUi(self, Class_DlogER_2Dcode):
        _translate = QtCore.QCoreApplication.translate
        Class_DlogER_2Dcode.setWindowTitle(_translate("Class_DlogER_2Dcode", "Dialog"))
        self.label.setText(_translate("Class_DlogER_2Dcode", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Edit Region</span></p></body></html>"))
        self.label_3.setText(_translate("Class_DlogER_2Dcode", "<html><head/><body><p>Use the frame to surround the area</p></body></html>"))
        self.label_2.setText(_translate("Class_DlogER_2Dcode", "To be measured"))
        self.label_4.setText(_translate("Class_DlogER_2Dcode", "Press the  \"OK \"button after setting "))
        self.label_5.setText(_translate("Class_DlogER_2Dcode", "is conpleted"))
        self.label_6.setText(_translate("Class_DlogER_2Dcode", "Inspection Region"))
        self.comBox_InspectionRegion_2Dcode.setItemText(0, _translate("Class_DlogER_2Dcode", "Rectangle"))
        self.label_7.setText(_translate("Class_DlogER_2Dcode", "Reference Image"))
        self.btn_referencImage_2Dcode.setText(_translate("Class_DlogER_2Dcode", "0001"))
        self.btn_OK_editRegion_2Dcode.setText(_translate("Class_DlogER_2Dcode", "OK"))
        self.btn_Cancel_editRegion_2Dcode.setText(_translate("Class_DlogER_2Dcode", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Class_DlogER_2Dcode = QtWidgets.QDialog()
    ui = Ui_Class_DlogER_2Dcode()
    ui.setupUi(Class_DlogER_2Dcode)
    Class_DlogER_2Dcode.show()
    sys.exit(app.exec_())

