# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I_DlogV_2Dcode.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Class_DlogV_2Dcode(object):
    def setupUi(self, Class_DlogV_2Dcode):
        Class_DlogV_2Dcode.setObjectName("Class_DlogV_2Dcode")
        Class_DlogV_2Dcode.resize(494, 867)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Class_DlogV_2Dcode)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget_2 = QtWidgets.QWidget(Class_DlogV_2Dcode)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalWidget_2.setStyleSheet("background-color: rgb(32, 74, 135);")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label.setStyleSheet("color: rgb(238, 238, 236);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.horizontalWidget_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Class_DlogV_2Dcode)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 488, 731))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(400, 600))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalFrame_7 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.verticalFrame_7.setObjectName("verticalFrame_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalFrame_7)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalFrame_3 = QtWidgets.QFrame(self.verticalFrame_7)
        self.horizontalFrame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalFrame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame_3.setStyleSheet("\n"
"background-color: rgb(136, 138, 133);\n"
"color: rgb(0, 0, 0);")
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_4.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_10.addWidget(self.horizontalFrame_3)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.verticalFrame_7)
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.horizontalFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_3.setContentsMargins(30, 10, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.combox_Verification_V_2Dcode = QtWidgets.QComboBox(self.horizontalFrame_2)
        self.combox_Verification_V_2Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.combox_Verification_V_2Dcode.setObjectName("combox_Verification_V_2Dcode")
        self.combox_Verification_V_2Dcode.addItem("")
        self.combox_Verification_V_2Dcode.addItem("")
        self.combox_Verification_V_2Dcode.addItem("")
        self.horizontalLayout_3.addWidget(self.combox_Verification_V_2Dcode)
        self.verticalLayout_10.addWidget(self.horizontalFrame_2)
        self.verticalLayout_6.addWidget(self.verticalFrame_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalFrame_8 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalFrame_8.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.verticalFrame_8.setObjectName("verticalFrame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalFrame_8)
        self.verticalLayout_11.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_4.setMinimumSize(QtCore.QSize(0, 50))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.verticalLayout_9.addWidget(self.verticalFrame_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_13.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(20, -1, 10, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        self.btn_SelectData_V_2Dcode = QtWidgets.QPushButton(self.frame_2)
        self.btn_SelectData_V_2Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_SelectData_V_2Dcode.setObjectName("btn_SelectData_V_2Dcode")
        self.horizontalLayout_15.addWidget(self.btn_SelectData_V_2Dcode)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.horizontalFrame_8 = QtWidgets.QFrame(self.frame_2)
        self.horizontalFrame_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.horizontalFrame_8.setObjectName("horizontalFrame_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalFrame_8)
        self.horizontalLayout_14.setContentsMargins(20, 0, -1, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_5 = QtWidgets.QLabel(self.horizontalFrame_8)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.tedit_Measured_V_2Dcode = QtWidgets.QTextEdit(self.horizontalFrame_8)
        self.tedit_Measured_V_2Dcode.setMaximumSize(QtCore.QSize(80, 30))
        self.tedit_Measured_V_2Dcode.setObjectName("tedit_Measured_V_2Dcode")
        self.horizontalLayout_14.addWidget(self.tedit_Measured_V_2Dcode)
        self.verticalLayout_13.addWidget(self.horizontalFrame_8)
        self.horizontalFrame_6 = QtWidgets.QFrame(self.frame_2)
        self.horizontalFrame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_11.setContentsMargins(20, 0, 10, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.horizontalFrame_6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.tedit_TextCalled_V_2Dcode = QtWidgets.QTextEdit(self.horizontalFrame_6)
        self.tedit_TextCalled_V_2Dcode.setMaximumSize(QtCore.QSize(80, 30))
        self.tedit_TextCalled_V_2Dcode.setObjectName("tedit_TextCalled_V_2Dcode")
        self.horizontalLayout_11.addWidget(self.tedit_TextCalled_V_2Dcode)
        self.verticalLayout_13.addWidget(self.horizontalFrame_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(20, -1, 10, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.btn_SetPerItem_V_2Dcode = QtWidgets.QPushButton(self.frame_2)
        self.btn_SetPerItem_V_2Dcode.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_SetPerItem_V_2Dcode.setObjectName("btn_SetPerItem_V_2Dcode")
        self.horizontalLayout_10.addWidget(self.btn_SetPerItem_V_2Dcode)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_9)
        self.rererer = QtWidgets.QFrame(self.frame)
        self.rererer.setMinimumSize(QtCore.QSize(0, 300))
        self.rererer.setObjectName("rererer")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.rererer)
        self.verticalLayout_8.setContentsMargins(-1, 1, -1, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6.addWidget(self.rererer)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addWidget(self.frame)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalFrame = QtWidgets.QFrame(Class_DlogV_2Dcode)
        self.horizontalFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.horizontalFrame.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(10, 0, 10, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_OK_V_2Dcode = QtWidgets.QPushButton(self.horizontalFrame)
        self.btn_OK_V_2Dcode.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_OK_V_2Dcode.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_OK_V_2Dcode.setObjectName("btn_OK_V_2Dcode")
        self.horizontalLayout.addWidget(self.btn_OK_V_2Dcode)
        self.btn_Cancel_V_2Dcode = QtWidgets.QPushButton(self.horizontalFrame)
        self.btn_Cancel_V_2Dcode.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_Cancel_V_2Dcode.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(238, 238, 236);")
        self.btn_Cancel_V_2Dcode.setObjectName("btn_Cancel_V_2Dcode")
        self.horizontalLayout.addWidget(self.btn_Cancel_V_2Dcode)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Class_DlogV_2Dcode)
        QtCore.QMetaObject.connectSlotsByName(Class_DlogV_2Dcode)

    def retranslateUi(self, Class_DlogV_2Dcode):
        _translate = QtCore.QCoreApplication.translate
        Class_DlogV_2Dcode.setWindowTitle(_translate("Class_DlogV_2Dcode", "Dialog"))
        self.label.setText(_translate("Class_DlogV_2Dcode", "2D Code Reader   > Verification"))
        self.label_2.setText(_translate("Class_DlogV_2Dcode", "Verification"))
        self.label_3.setText(_translate("Class_DlogV_2Dcode", "Verification"))
        self.combox_Verification_V_2Dcode.setItemText(0, _translate("Class_DlogV_2Dcode", "OFF"))
        self.combox_Verification_V_2Dcode.setItemText(1, _translate("Class_DlogV_2Dcode", "ISO/IEC 15415"))
        self.combox_Verification_V_2Dcode.setItemText(2, _translate("Class_DlogV_2Dcode", "AIM DPM-1 -2006"))
        self.label_4.setText(_translate("Class_DlogV_2Dcode", "Judgment Conditions"))
        self.label_7.setText(_translate("Class_DlogV_2Dcode", "Overall Synbol Grade"))
        self.btn_SelectData_V_2Dcode.setText(_translate("Class_DlogV_2Dcode", "Select Data"))
        self.label_5.setText(_translate("Class_DlogV_2Dcode", "Measured    "))
        self.label_10.setText(_translate("Class_DlogV_2Dcode", "Text Called       "))
        self.btn_SetPerItem_V_2Dcode.setText(_translate("Class_DlogV_2Dcode", "Set Per Item"))
        self.btn_OK_V_2Dcode.setText(_translate("Class_DlogV_2Dcode", "OK"))
        self.btn_Cancel_V_2Dcode.setText(_translate("Class_DlogV_2Dcode", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Class_DlogV_2Dcode = QtWidgets.QDialog()
    ui = Ui_Class_DlogV_2Dcode()
    ui.setupUi(Class_DlogV_2Dcode)
    Class_DlogV_2Dcode.show()
    sys.exit(app.exec_())

