from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Class_DlogJC_1Dcode(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        #Dialog.move(1920-1252+60, 310)
        Dialog.move(1920 - 1236 + 400 + 60, 310)
        #Dialog.resize(1160, 700)
        Dialog.resize(820, 700)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(400, 650))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setStyleSheet("background-color: rgb(0, 58, 88);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 551, 1020))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollAreaWidgetContents.setMouseTracking(False)
        self.scrollAreaWidgetContents.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_7.setMinimumSize(QtCore.QSize(450, 1000))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_15.addWidget(self.label_5)
        self.frame_3 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 10))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 20))
        self.label_6.setMaximumSize(QtCore.QSize(100, 20))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.rbtn_SingleOfConditi_JC_TableSetting = QtWidgets.QRadioButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtn_SingleOfConditi_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.rbtn_SingleOfConditi_JC_TableSetting.setSizePolicy(sizePolicy)
        self.rbtn_SingleOfConditi_JC_TableSetting.setMinimumSize(QtCore.QSize(100, 20))
        self.rbtn_SingleOfConditi_JC_TableSetting.setMaximumSize(QtCore.QSize(100, 20))
        self.rbtn_SingleOfConditi_JC_TableSetting.setObjectName("rbtn_SingleOfConditi_JC_TableSetting")
        self.horizontalLayout_11.addWidget(self.rbtn_SingleOfConditi_JC_TableSetting)
        self.rbtn_MultiOfConditi_JC_TableSetting = QtWidgets.QRadioButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtn_MultiOfConditi_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.rbtn_MultiOfConditi_JC_TableSetting.setSizePolicy(sizePolicy)
        self.rbtn_MultiOfConditi_JC_TableSetting.setMinimumSize(QtCore.QSize(100, 20))
        self.rbtn_MultiOfConditi_JC_TableSetting.setMaximumSize(QtCore.QSize(100, 20))
        self.rbtn_MultiOfConditi_JC_TableSetting.setObjectName("rbtn_MultiOfConditi_JC_TableSetting")
        self.horizontalLayout_11.addWidget(self.rbtn_MultiOfConditi_JC_TableSetting)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.btn_CondiList_JC_TableSetting = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_CondiList_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.btn_CondiList_JC_TableSetting.setSizePolicy(sizePolicy)
        self.btn_CondiList_JC_TableSetting.setMinimumSize(QtCore.QSize(100, 20))
        self.btn_CondiList_JC_TableSetting.setMaximumSize(QtCore.QSize(100, 20))
        self.btn_CondiList_JC_TableSetting.setObjectName("btn_CondiList_JC_TableSetting")
        self.horizontalLayout_12.addWidget(self.btn_CondiList_JC_TableSetting)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(100, 20))
        self.label_9.setMaximumSize(QtCore.QSize(100, 20))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.combox_DataRange_JC_TableSetting = QtWidgets.QComboBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combox_DataRange_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.combox_DataRange_JC_TableSetting.setSizePolicy(sizePolicy)
        self.combox_DataRange_JC_TableSetting.setMinimumSize(QtCore.QSize(100, 20))
        self.combox_DataRange_JC_TableSetting.setMaximumSize(QtCore.QSize(100, 20))
        self.combox_DataRange_JC_TableSetting.setObjectName("combox_DataRange_JC_TableSetting")
        self.horizontalLayout_13.addWidget(self.combox_DataRange_JC_TableSetting)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(70, 20))
        self.label_10.setMaximumSize(QtCore.QSize(70, 20))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_14.addWidget(self.label_10)
        self.lab_StartDigit_JC_TableSetting = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_StartDigit_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.lab_StartDigit_JC_TableSetting.setSizePolicy(sizePolicy)
        self.lab_StartDigit_JC_TableSetting.setMinimumSize(QtCore.QSize(20, 20))
        self.lab_StartDigit_JC_TableSetting.setMaximumSize(QtCore.QSize(20, 20))
        self.lab_StartDigit_JC_TableSetting.setObjectName("lab_StartDigit_JC_TableSetting")
        self.horizontalLayout_14.addWidget(self.lab_StartDigit_JC_TableSetting)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(50, 20))
        self.label_12.setMaximumSize(QtCore.QSize(50, 20))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.lab_RangeDigit_JC_TableSetting = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_RangeDigit_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.lab_RangeDigit_JC_TableSetting.setSizePolicy(sizePolicy)
        self.lab_RangeDigit_JC_TableSetting.setMinimumSize(QtCore.QSize(20, 20))
        self.lab_RangeDigit_JC_TableSetting.setMaximumSize(QtCore.QSize(20, 20))
        self.lab_RangeDigit_JC_TableSetting.setObjectName("lab_RangeDigit_JC_TableSetting")
        self.horizontalLayout_14.addWidget(self.lab_RangeDigit_JC_TableSetting)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.btn_ReferecPattern_JC_TableSetting = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ReferecPattern_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.btn_ReferecPattern_JC_TableSetting.setSizePolicy(sizePolicy)
        self.btn_ReferecPattern_JC_TableSetting.setMinimumSize(QtCore.QSize(100, 20))
        self.btn_ReferecPattern_JC_TableSetting.setMaximumSize(QtCore.QSize(100, 20))
        self.btn_ReferecPattern_JC_TableSetting.setObjectName("btn_ReferecPattern_JC_TableSetting")
        self.horizontalLayout_16.addWidget(self.btn_ReferecPattern_JC_TableSetting)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(150, 20))
        self.label_15.setMaximumSize(QtCore.QSize(150, 20))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.btn_CopyFromReadData_JC_TableSetting = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_CopyFromReadData_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.btn_CopyFromReadData_JC_TableSetting.setSizePolicy(sizePolicy)
        self.btn_CopyFromReadData_JC_TableSetting.setMinimumSize(QtCore.QSize(150, 20))
        self.btn_CopyFromReadData_JC_TableSetting.setMaximumSize(QtCore.QSize(150, 20))
        self.btn_CopyFromReadData_JC_TableSetting.setObjectName("btn_CopyFromReadData_JC_TableSetting")
        self.horizontalLayout_15.addWidget(self.btn_CopyFromReadData_JC_TableSetting)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.ledit_CopyFromReadData_JC_TableSetting = QtWidgets.QLineEdit(self.frame_3)
        self.ledit_CopyFromReadData_JC_TableSetting.setObjectName("ledit_CopyFromReadData_JC_TableSetting")
        self.horizontalLayout_17.addWidget(self.ledit_CopyFromReadData_JC_TableSetting)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(150, 20))
        self.label_16.setMaximumSize(QtCore.QSize(150, 20))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.btn_ConversionSetting_JC_TableSetting = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ConversionSetting_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.btn_ConversionSetting_JC_TableSetting.setSizePolicy(sizePolicy)
        self.btn_ConversionSetting_JC_TableSetting.setMinimumSize(QtCore.QSize(150, 20))
        self.btn_ConversionSetting_JC_TableSetting.setMaximumSize(QtCore.QSize(150, 20))
        self.btn_ConversionSetting_JC_TableSetting.setObjectName("btn_ConversionSetting_JC_TableSetting")
        self.horizontalLayout_10.addWidget(self.btn_ConversionSetting_JC_TableSetting)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(0, 20))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_10.addWidget(self.label_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.lab_CollationResult_JC_TableSetting = QtWidgets.QLabel(self.frame_3)
        self.lab_CollationResult_JC_TableSetting.setObjectName("lab_CollationResult_JC_TableSetting")
        self.horizontalLayout_18.addWidget(self.lab_CollationResult_JC_TableSetting)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.verticalLayout_15.addWidget(self.frame_3)
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_26 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(100, 20))
        self.label_26.setMaximumSize(QtCore.QSize(100, 20))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_20.addWidget(self.label_26)
        spacerItem9 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.ledit_UpperLimitLengData_JC_TableSetting = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_UpperLimitLengData_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.ledit_UpperLimitLengData_JC_TableSetting.setSizePolicy(sizePolicy)
        self.ledit_UpperLimitLengData_JC_TableSetting.setMinimumSize(QtCore.QSize(225, 20))
        self.ledit_UpperLimitLengData_JC_TableSetting.setMaximumSize(QtCore.QSize(225, 20))
        self.ledit_UpperLimitLengData_JC_TableSetting.setObjectName("ledit_UpperLimitLengData_JC_TableSetting")
        self.horizontalLayout_20.addWidget(self.ledit_UpperLimitLengData_JC_TableSetting)
        spacerItem10 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_27 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(100, 20))
        self.label_27.setMaximumSize(QtCore.QSize(100, 20))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_4.addWidget(self.label_27)
        spacerItem11 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.lab_MeasuredReadDataLeng_JC_TableSetting = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_MeasuredReadDataLeng_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.lab_MeasuredReadDataLeng_JC_TableSetting.setSizePolicy(sizePolicy)
        self.lab_MeasuredReadDataLeng_JC_TableSetting.setMinimumSize(QtCore.QSize(100, 20))
        self.lab_MeasuredReadDataLeng_JC_TableSetting.setMaximumSize(QtCore.QSize(100, 20))
        self.lab_MeasuredReadDataLeng_JC_TableSetting.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_MeasuredReadDataLeng_JC_TableSetting.setObjectName("lab_MeasuredReadDataLeng_JC_TableSetting")
        self.horizontalLayout_4.addWidget(self.lab_MeasuredReadDataLeng_JC_TableSetting)
        spacerItem12 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_28 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(100, 20))
        self.label_28.setMaximumSize(QtCore.QSize(100, 20))
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_19.addWidget(self.label_28)
        spacerItem13 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem13)
        self.ledit_LowerLimitLengData_JC_TableSetting = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_LowerLimitLengData_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.ledit_LowerLimitLengData_JC_TableSetting.setSizePolicy(sizePolicy)
        self.ledit_LowerLimitLengData_JC_TableSetting.setMinimumSize(QtCore.QSize(225, 20))
        self.ledit_LowerLimitLengData_JC_TableSetting.setMaximumSize(QtCore.QSize(225, 20))
        self.ledit_LowerLimitLengData_JC_TableSetting.setObjectName("ledit_LowerLimitLengData_JC_TableSetting")
        self.horizontalLayout_19.addWidget(self.ledit_LowerLimitLengData_JC_TableSetting)
        spacerItem14 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem14)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_15.addWidget(self.frame_6)
        self.label_25 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(0, 30))
        self.label_25.setObjectName("label_25")
        self.verticalLayout_15.addWidget(self.label_25)
        self.frame_5 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem15 = QtWidgets.QSpacerItem(225, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(70, 20))
        self.label_22.setMaximumSize(QtCore.QSize(70, 20))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_6.addWidget(self.label_22)
        spacerItem16 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(70, 20))
        self.label_23.setMaximumSize(QtCore.QSize(70, 20))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_6.addWidget(self.label_23)
        spacerItem17 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 20))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem18 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)
        self.ledit_UpperLimitPositX_JC_TableSetting = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_UpperLimitPositX_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.ledit_UpperLimitPositX_JC_TableSetting.setSizePolicy(sizePolicy)
        self.ledit_UpperLimitPositX_JC_TableSetting.setMinimumSize(QtCore.QSize(100, 20))
        self.ledit_UpperLimitPositX_JC_TableSetting.setMaximumSize(QtCore.QSize(100, 20))
        self.ledit_UpperLimitPositX_JC_TableSetting.setObjectName("ledit_UpperLimitPositX_JC_TableSetting")
        self.horizontalLayout_3.addWidget(self.ledit_UpperLimitPositX_JC_TableSetting)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem19)
        self.ledit_UpperLimitPositY_JC_TableSetting = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_UpperLimitPositY_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.ledit_UpperLimitPositY_JC_TableSetting.setSizePolicy(sizePolicy)
        self.ledit_UpperLimitPositY_JC_TableSetting.setMinimumSize(QtCore.QSize(100, 20))
        self.ledit_UpperLimitPositY_JC_TableSetting.setMaximumSize(QtCore.QSize(100, 20))
        self.ledit_UpperLimitPositY_JC_TableSetting.setObjectName("ledit_UpperLimitPositY_JC_TableSetting")
        self.horizontalLayout_3.addWidget(self.ledit_UpperLimitPositY_JC_TableSetting)
        spacerItem20 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(100, 0))
        self.label_19.setMaximumSize(QtCore.QSize(100, 20))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_8.addWidget(self.label_19)
        spacerItem21 = QtWidgets.QSpacerItem(135, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem21)
        self.lab_MeasuredPositX_JC_TableSetting = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_MeasuredPositX_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.lab_MeasuredPositX_JC_TableSetting.setSizePolicy(sizePolicy)
        self.lab_MeasuredPositX_JC_TableSetting.setMinimumSize(QtCore.QSize(40, 0))
        self.lab_MeasuredPositX_JC_TableSetting.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_MeasuredPositX_JC_TableSetting.setObjectName("lab_MeasuredPositX_JC_TableSetting")
        self.horizontalLayout_8.addWidget(self.lab_MeasuredPositX_JC_TableSetting)
        spacerItem22 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem22)
        self.lab_MeasuredPositY_JC_TableSetting = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_MeasuredPositY_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.lab_MeasuredPositY_JC_TableSetting.setSizePolicy(sizePolicy)
        self.lab_MeasuredPositY_JC_TableSetting.setMinimumSize(QtCore.QSize(40, 20))
        self.lab_MeasuredPositY_JC_TableSetting.setMaximumSize(QtCore.QSize(40, 20))
        self.lab_MeasuredPositY_JC_TableSetting.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_MeasuredPositY_JC_TableSetting.setObjectName("lab_MeasuredPositY_JC_TableSetting")
        self.horizontalLayout_8.addWidget(self.lab_MeasuredPositY_JC_TableSetting)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem23)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_20 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(100, 0))
        self.label_20.setMaximumSize(QtCore.QSize(100, 20))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        spacerItem24 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem24)
        self.ledit_LowerLimitPositX_JC_TableSetting = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_LowerLimitPositX_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.ledit_LowerLimitPositX_JC_TableSetting.setSizePolicy(sizePolicy)
        self.ledit_LowerLimitPositX_JC_TableSetting.setMinimumSize(QtCore.QSize(100, 0))
        self.ledit_LowerLimitPositX_JC_TableSetting.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ledit_LowerLimitPositX_JC_TableSetting.setObjectName("ledit_LowerLimitPositX_JC_TableSetting")
        self.horizontalLayout_9.addWidget(self.ledit_LowerLimitPositX_JC_TableSetting)
        spacerItem25 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem25)
        self.ledit_LowerLimitPositY_JC_TableSetting = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_LowerLimitPositY_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.ledit_LowerLimitPositY_JC_TableSetting.setSizePolicy(sizePolicy)
        self.ledit_LowerLimitPositY_JC_TableSetting.setMinimumSize(QtCore.QSize(100, 20))
        self.ledit_LowerLimitPositY_JC_TableSetting.setMaximumSize(QtCore.QSize(100, 20))
        self.ledit_LowerLimitPositY_JC_TableSetting.setObjectName("ledit_LowerLimitPositY_JC_TableSetting")
        self.horizontalLayout_9.addWidget(self.ledit_LowerLimitPositY_JC_TableSetting)
        spacerItem26 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem26)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_15.addWidget(self.frame_5)
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_15.addWidget(self.label_4)
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 20))
        self.label_7.setMaximumSize(QtCore.QSize(100, 20))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem27)
        self.ledit_UpperLimitDetecAngle_JC_TableSetting = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_UpperLimitDetecAngle_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.ledit_UpperLimitDetecAngle_JC_TableSetting.setSizePolicy(sizePolicy)
        self.ledit_UpperLimitDetecAngle_JC_TableSetting.setMinimumSize(QtCore.QSize(225, 20))
        self.ledit_UpperLimitDetecAngle_JC_TableSetting.setMaximumSize(QtCore.QSize(225, 20))
        self.ledit_UpperLimitDetecAngle_JC_TableSetting.setObjectName("ledit_UpperLimitDetecAngle_JC_TableSetting")
        self.horizontalLayout_7.addWidget(self.ledit_UpperLimitDetecAngle_JC_TableSetting)
        spacerItem28 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem28)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(100, 20))
        self.label_8.setMaximumSize(QtCore.QSize(100, 20))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        spacerItem29 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem29)
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(100, 0))
        self.label_31.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_5.addWidget(self.label_31)
        spacerItem30 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem30)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_30 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(100, 20))
        self.label_30.setMaximumSize(QtCore.QSize(100, 20))
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_21.addWidget(self.label_30)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem31)
        self.ledit_LowerLimitDetecAngle_JC_TableSetting = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_LowerLimitDetecAngle_JC_TableSetting.sizePolicy().hasHeightForWidth())
        self.ledit_LowerLimitDetecAngle_JC_TableSetting.setSizePolicy(sizePolicy)
        self.ledit_LowerLimitDetecAngle_JC_TableSetting.setMinimumSize(QtCore.QSize(225, 20))
        self.ledit_LowerLimitDetecAngle_JC_TableSetting.setMaximumSize(QtCore.QSize(225, 20))
        self.ledit_LowerLimitDetecAngle_JC_TableSetting.setObjectName("ledit_LowerLimitDetecAngle_JC_TableSetting")
        self.horizontalLayout_21.addWidget(self.ledit_LowerLimitDetecAngle_JC_TableSetting)
        spacerItem32 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem32)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_15.addWidget(self.frame_4)
        spacerItem33 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem33)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem34)
        self.btn_Ok_JC_TableSetting = QtWidgets.QPushButton(self.frame_2)
        self.btn_Ok_JC_TableSetting.setObjectName("btn_Ok_JC_TableSetting")
        self.horizontalLayout.addWidget(self.btn_Ok_JC_TableSetting)
        self.btn_Cancel_JC_TableSetting = QtWidgets.QPushButton(self.frame_2)
        self.btn_Cancel_JC_TableSetting.setObjectName("btn_Cancel_JC_TableSetting")
        self.horizontalLayout.addWidget(self.btn_Cancel_JC_TableSetting)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_14.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "1D Code Reader > Judgment Conditions "))
        self.label_5.setText(_translate("Dialog", "Data Collation"))
        self.label_6.setText(_translate("Dialog", "Condition"))
        self.rbtn_SingleOfConditi_JC_TableSetting.setText(_translate("Dialog", "Single"))
        self.rbtn_MultiOfConditi_JC_TableSetting.setText(_translate("Dialog", "Multiple"))
        self.btn_CondiList_JC_TableSetting.setText(_translate("Dialog", "Condition List"))
        self.label_9.setText(_translate("Dialog", "Data Range"))
        self.label_10.setText(_translate("Dialog", "Start Digit :"))
        self.lab_StartDigit_JC_TableSetting.setText(_translate("Dialog", "1"))
        self.label_12.setText(_translate("Dialog", "Range :"))
        self.lab_RangeDigit_JC_TableSetting.setText(_translate("Dialog", "10"))
        self.label_14.setText(_translate("Dialog", "Read Data"))
        self.btn_ReferecPattern_JC_TableSetting.setText(_translate("Dialog", ">>"))
        self.label_15.setText(_translate("Dialog", "Reference Pattern"))
        self.btn_CopyFromReadData_JC_TableSetting.setText(_translate("Dialog", "Copy from read data"))
        self.label_16.setText(_translate("Dialog", "(Converted)"))
        self.btn_ConversionSetting_JC_TableSetting.setText(_translate("Dialog", "Conversion Settings"))
        self.label_17.setText(_translate("Dialog", "Collation Result"))
        self.lab_CollationResult_JC_TableSetting.setText(_translate("Dialog", "OK"))
        self.label_2.setText(_translate("Dialog", "Read data length"))
        self.label_26.setText(_translate("Dialog", "Upper Limit"))
        self.label_27.setText(_translate("Dialog", "Measured"))
        self.lab_MeasuredReadDataLeng_JC_TableSetting.setText(_translate("Dialog", "100"))
        self.label_28.setText(_translate("Dialog", "Lower Limit"))
        self.label_25.setText(_translate("Dialog", "Position"))
        self.label_22.setText(_translate("Dialog", "Position X"))
        self.label_23.setText(_translate("Dialog", "Position Y"))
        self.label_3.setText(_translate("Dialog", "Upper Limit"))
        self.label_19.setText(_translate("Dialog", "Measured"))
        self.lab_MeasuredPositX_JC_TableSetting.setText(_translate("Dialog", "10000"))
        self.lab_MeasuredPositY_JC_TableSetting.setText(_translate("Dialog", "0"))
        self.label_20.setText(_translate("Dialog", "Lower Limit"))
        self.label_4.setText(_translate("Dialog", "Detected Angle"))
        self.label_7.setText(_translate("Dialog", "Upper Limit"))
        self.label_8.setText(_translate("Dialog", "Measured"))
        self.label_31.setText(_translate("Dialog", "100"))
        self.label_30.setText(_translate("Dialog", "Lower Limit"))
        self.btn_Ok_JC_TableSetting.setText(_translate("Dialog", "OK"))
        self.btn_Cancel_JC_TableSetting.setText(_translate("Dialog", "Cancel"))


