# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I_DlogRDS_2Dcode.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Class_DlogRDS_2Dcode(object):
    def setupUi(self, Class_DlogRDS_2Dcode):
        Class_DlogRDS_2Dcode.setObjectName("Class_DlogRDS_2Dcode")
        Class_DlogRDS_2Dcode.resize(505, 860)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Class_DlogRDS_2Dcode)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget_2 = QtWidgets.QWidget(Class_DlogRDS_2Dcode)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalWidget_2.setStyleSheet("background-color: rgb(32, 74, 135);")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label.setStyleSheet("color: rgb(238, 238, 236);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.horizontalWidget_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(Class_DlogRDS_2Dcode)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -78, 485, 802))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(400, 800))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalFrame_7 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_7.setMaximumSize(QtCore.QSize(16777215, 150))
        self.verticalFrame_7.setObjectName("verticalFrame_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalFrame_7)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalFrame_3 = QtWidgets.QFrame(self.verticalFrame_7)
        self.horizontalFrame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame_3.setStyleSheet("\n"
"background-color: rgb(136, 138, 133);\n"
"color: rgb(0, 0, 0);")
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_4.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_10.addWidget(self.horizontalFrame_3)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.verticalFrame_7)
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_3.setContentsMargins(30, 5, -1, 5)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.tedit_StartDigit_RDS_2Dcode = QtWidgets.QTextEdit(self.horizontalFrame_2)
        self.tedit_StartDigit_RDS_2Dcode.setMaximumSize(QtCore.QSize(80, 30))
        self.tedit_StartDigit_RDS_2Dcode.setObjectName("tedit_StartDigit_RDS_2Dcode")
        self.horizontalLayout_3.addWidget(self.tedit_StartDigit_RDS_2Dcode)
        self.verticalLayout_10.addWidget(self.horizontalFrame_2)
        self.horizontalFrame = QtWidgets.QFrame(self.verticalFrame_7)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_13.setContentsMargins(30, 0, 10, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.tedit_ReadDataLength_RDS_2Dcode = QtWidgets.QTextEdit(self.horizontalFrame)
        self.tedit_ReadDataLength_RDS_2Dcode.setMaximumSize(QtCore.QSize(80, 30))
        self.tedit_ReadDataLength_RDS_2Dcode.setObjectName("tedit_ReadDataLength_RDS_2Dcode")
        self.horizontalLayout_13.addWidget(self.tedit_ReadDataLength_RDS_2Dcode)
        self.verticalLayout_10.addWidget(self.horizontalFrame)
        self.verticalLayout_6.addWidget(self.verticalFrame_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalFrame_8 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_8.setMinimumSize(QtCore.QSize(0, 50))
        self.verticalFrame_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalFrame_8.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.verticalFrame_8.setObjectName("verticalFrame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalFrame_8)
        self.verticalLayout_11.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.verticalLayout_9.addWidget(self.verticalFrame_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cbox_SplitData_RDS_2Dcode = QtWidgets.QCheckBox(self.frame_2)
        self.cbox_SplitData_RDS_2Dcode.setObjectName("cbox_SplitData_RDS_2Dcode")
        self.horizontalLayout_12.addWidget(self.cbox_SplitData_RDS_2Dcode)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.horizontalFrame_6 = QtWidgets.QFrame(self.frame_2)
        self.horizontalFrame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_11.setContentsMargins(1, -1, 10, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.btn_SplitSetting_RDS_2Dcode = QtWidgets.QPushButton(self.horizontalFrame_6)
        self.btn_SplitSetting_RDS_2Dcode.setObjectName("btn_SplitSetting_RDS_2Dcode")
        self.horizontalLayout_11.addWidget(self.btn_SplitSetting_RDS_2Dcode)
        self.verticalLayout_13.addWidget(self.horizontalFrame_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(20, -1, 10, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cbox_OutputLength_RDS_2Dcode = QtWidgets.QCheckBox(self.frame_2)
        self.cbox_OutputLength_RDS_2Dcode.setObjectName("cbox_OutputLength_RDS_2Dcode")
        self.horizontalLayout_10.addWidget(self.cbox_OutputLength_RDS_2Dcode)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.dsadsad = QtWidgets.QFrame(self.frame_2)
        self.dsadsad.setMaximumSize(QtCore.QSize(16777215, 50))
        self.dsadsad.setObjectName("dsadsad")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.dsadsad)
        self.horizontalLayout_9.setContentsMargins(20, -1, 10, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.dsadsad)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.tedit_FillingCharacter_RDS_2Dcode = QtWidgets.QTextEdit(self.dsadsad)
        self.tedit_FillingCharacter_RDS_2Dcode.setMaximumSize(QtCore.QSize(80, 30))
        self.tedit_FillingCharacter_RDS_2Dcode.setObjectName("tedit_FillingCharacter_RDS_2Dcode")
        self.horizontalLayout_9.addWidget(self.tedit_FillingCharacter_RDS_2Dcode)
        self.verticalLayout_13.addWidget(self.dsadsad)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(20, -1, 10, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.cbox_CallTextError_RDS_2Dcode = QtWidgets.QCheckBox(self.frame_2)
        self.cbox_CallTextError_RDS_2Dcode.setObjectName("cbox_CallTextError_RDS_2Dcode")
        self.horizontalLayout_17.addWidget(self.cbox_CallTextError_RDS_2Dcode)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.verticalFrame_81 = QtWidgets.QFrame(self.frame_2)
        self.verticalFrame_81.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalFrame_81.setObjectName("verticalFrame_81")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.verticalFrame_81)
        self.horizontalLayout_16.setContentsMargins(20, -1, 10, -1)
        self.horizontalLayout_16.setSpacing(60)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.verticalFrame_81)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.tedit_TextCalled_RDS_2Dcode = QtWidgets.QTextEdit(self.verticalFrame_81)
        self.tedit_TextCalled_RDS_2Dcode.setMaximumSize(QtCore.QSize(80, 16777215))
        self.tedit_TextCalled_RDS_2Dcode.setObjectName("tedit_TextCalled_RDS_2Dcode")
        self.horizontalLayout_16.addWidget(self.tedit_TextCalled_RDS_2Dcode)
        self.verticalLayout_13.addWidget(self.verticalFrame_81)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalFrame_82 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_82.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalFrame_82.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.verticalFrame_82.setObjectName("verticalFrame_82")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalFrame_82)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.verticalFrame_82)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.verticalLayout_8.addWidget(self.verticalFrame_82)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalFrame_11 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_11.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalFrame_11.setObjectName("verticalFrame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.verticalFrame_11)
        self.horizontalLayout_6.setContentsMargins(20, -1, 10, -1)
        self.horizontalLayout_6.setSpacing(30)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbox_OutputIdentifier_RDS_2Dcode = QtWidgets.QCheckBox(self.verticalFrame_11)
        self.cbox_OutputIdentifier_RDS_2Dcode.setObjectName("cbox_OutputIdentifier_RDS_2Dcode")
        self.horizontalLayout_6.addWidget(self.cbox_OutputIdentifier_RDS_2Dcode)
        self.verticalLayout_12.addWidget(self.verticalFrame_11)
        self.frame1 = QtWidgets.QFrame(self.frame)
        self.frame1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame1.setObjectName("frame1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout_7.setContentsMargins(50, -1, 10, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.frame1)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.verticalLayout_12.addWidget(self.frame1)
        self.verticalFrame_83 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_83.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalFrame_83.setObjectName("verticalFrame_83")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.verticalFrame_83)
        self.horizontalLayout_18.setContentsMargins(20, -1, 10, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.cbox_Ignore_RDS_2Dcode = QtWidgets.QCheckBox(self.verticalFrame_83)
        self.cbox_Ignore_RDS_2Dcode.setObjectName("cbox_Ignore_RDS_2Dcode")
        self.horizontalLayout_18.addWidget(self.cbox_Ignore_RDS_2Dcode)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.cbox_Output_RDS_2Dcode = QtWidgets.QCheckBox(self.verticalFrame_83)
        self.cbox_Output_RDS_2Dcode.setObjectName("cbox_Output_RDS_2Dcode")
        self.horizontalLayout_18.addWidget(self.cbox_Output_RDS_2Dcode)
        self.verticalLayout_12.addWidget(self.verticalFrame_83)
        self.verticalLayout_8.addLayout(self.verticalLayout_12)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addWidget(self.frame)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalFrame1 = QtWidgets.QFrame(Class_DlogRDS_2Dcode)
        self.horizontalFrame1.setMinimumSize(QtCore.QSize(0, 80))
        self.horizontalFrame1.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.horizontalFrame1.setObjectName("horizontalFrame1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame1)
        self.horizontalLayout.setContentsMargins(10, 0, 10, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.btn_OK_RDS_2Dcode = QtWidgets.QPushButton(self.horizontalFrame1)
        self.btn_OK_RDS_2Dcode.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_OK_RDS_2Dcode.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_OK_RDS_2Dcode.setObjectName("btn_OK_RDS_2Dcode")
        self.horizontalLayout.addWidget(self.btn_OK_RDS_2Dcode)
        self.btn_Cancel_RDS_2Dcode = QtWidgets.QPushButton(self.horizontalFrame1)
        self.btn_Cancel_RDS_2Dcode.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_Cancel_RDS_2Dcode.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(238, 238, 236);")
        self.btn_Cancel_RDS_2Dcode.setObjectName("btn_Cancel_RDS_2Dcode")
        self.horizontalLayout.addWidget(self.btn_Cancel_RDS_2Dcode)
        self.verticalLayout.addWidget(self.horizontalFrame1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Class_DlogRDS_2Dcode)
        QtCore.QMetaObject.connectSlotsByName(Class_DlogRDS_2Dcode)

    def retranslateUi(self, Class_DlogRDS_2Dcode):
        _translate = QtCore.QCoreApplication.translate
        Class_DlogRDS_2Dcode.setWindowTitle(_translate("Class_DlogRDS_2Dcode", "Dialog"))
        self.label.setText(_translate("Class_DlogRDS_2Dcode", "2D Code Reader   > Details of Read Data Setting"))
        self.label_2.setText(_translate("Class_DlogRDS_2Dcode", "Primary Settings"))
        self.label_3.setText(_translate("Class_DlogRDS_2Dcode", "Start Digit"))
        self.label_16.setText(_translate("Class_DlogRDS_2Dcode", "Read Data Length "))
        self.label_4.setText(_translate("Class_DlogRDS_2Dcode", "Options"))
        self.cbox_SplitData_RDS_2Dcode.setText(_translate("Class_DlogRDS_2Dcode", "Split Data "))
        self.btn_SplitSetting_RDS_2Dcode.setText(_translate("Class_DlogRDS_2Dcode", "Split Setting"))
        self.cbox_OutputLength_RDS_2Dcode.setText(_translate("Class_DlogRDS_2Dcode", "Output Fixed Length"))
        self.label_6.setText(_translate("Class_DlogRDS_2Dcode", "Filling Character (1 byte)     "))
        self.cbox_CallTextError_RDS_2Dcode.setText(_translate("Class_DlogRDS_2Dcode", "Call Text at Read Error "))
        self.label_17.setText(_translate("Class_DlogRDS_2Dcode", "Text Called "))
        self.label_8.setText(_translate("Class_DlogRDS_2Dcode", "Action to Protocols"))
        self.cbox_OutputIdentifier_RDS_2Dcode.setText(_translate("Class_DlogRDS_2Dcode", "Output Symbol Identifier"))
        self.label_11.setText(_translate("Class_DlogRDS_2Dcode", "Extended Channel Interpetation"))
        self.cbox_Ignore_RDS_2Dcode.setText(_translate("Class_DlogRDS_2Dcode", "Ignore"))
        self.cbox_Output_RDS_2Dcode.setText(_translate("Class_DlogRDS_2Dcode", "Output "))
        self.btn_OK_RDS_2Dcode.setText(_translate("Class_DlogRDS_2Dcode", "OK"))
        self.btn_Cancel_RDS_2Dcode.setText(_translate("Class_DlogRDS_2Dcode", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Class_DlogRDS_2Dcode = QtWidgets.QDialog()
    ui = Ui_Class_DlogRDS_2Dcode()
    ui.setupUi(Class_DlogRDS_2Dcode)
    Class_DlogRDS_2Dcode.show()
    sys.exit(app.exec_())

