from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QPushButton,QHBoxLayout, QGridLayout, QApplication

from Detection_1DCode.XLA.roi import MyLabel
import tkinter as tk
root = tk.Tk()
width_px = int(root.winfo_screenwidth())
height_px = int(root.winfo_screenheight())


class Ui_Class_1Dcode(object):
    def setupUi(self, Ui_Class_1Dcode):
        Ui_Class_1Dcode.setObjectName("Ui_Class_1Dcode")

        Ui_Class_1Dcode.move(0, height_px*0.2)
        Ui_Class_1Dcode.resize(width_px, height_px*0.8)
        Ui_Class_1Dcode.setWindowFlag(QtCore.Qt.FramelessWindowHint)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Ui_Class_1Dcode)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vert = QtWidgets.QFrame(Ui_Class_1Dcode)
        self.vert.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.vert.setObjectName("vert")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.vert)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.vert)
        self.frame.setMinimumSize(QtCore.QSize(100, 100))
        self.frame.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_22.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_22.setSpacing(10)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalFrame = QtWidgets.QFrame(self.frame)
        self.verticalFrame.setStyleSheet("color: rgb(238, 238, 236);")
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lab_CommandFirst_1Dcode = QtWidgets.QLabel(self.verticalFrame)
        self.lab_CommandFirst_1Dcode.setText("")
        self.lab_CommandFirst_1Dcode.setObjectName("lab_CommandFirst_1Dcode")
        self.verticalLayout_4.addWidget(self.lab_CommandFirst_1Dcode)
        self.lab_CommandSecond_1Dcode = QtWidgets.QLabel(self.verticalFrame)
        self.lab_CommandSecond_1Dcode.setText("")
        self.lab_CommandSecond_1Dcode.setObjectName("lab_CommandSecond_1Dcode")
        self.verticalLayout_4.addWidget(self.lab_CommandSecond_1Dcode)
        self.lab_CommandThird_1Dcode = QtWidgets.QLabel(self.verticalFrame)
        self.lab_CommandThird_1Dcode.setText("")
        self.lab_CommandThird_1Dcode.setObjectName("lab_CommandThird_1Dcode")
        self.verticalLayout_4.addWidget(self.lab_CommandThird_1Dcode)
        self.horizontalLayout_13.addWidget(self.verticalFrame)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_13)
        self.verticalFrame_2 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_25.addItem(spacerItem)
        self.spinBox_Paper_1Dcode = QtWidgets.QSpinBox(self.verticalFrame_2)
        self.spinBox_Paper_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.spinBox_Paper_1Dcode.setObjectName("spinBox_Paper_1Dcode")
        self.verticalLayout_25.addWidget(self.spinBox_Paper_1Dcode)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btn_LelfCommand_1Dcode = QtWidgets.QPushButton(self.verticalFrame_2)
        self.btn_LelfCommand_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_LelfCommand_1Dcode.setObjectName("btn_LelfCommand_1Dcode")
        self.horizontalLayout_23.addWidget(self.btn_LelfCommand_1Dcode)
        self.btn_RightCommand_1Dcode = QtWidgets.QPushButton(self.verticalFrame_2)
        self.btn_RightCommand_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_RightCommand_1Dcode.setObjectName("btn_RightCommand_1Dcode")
        self.horizontalLayout_23.addWidget(self.btn_RightCommand_1Dcode)
        self.verticalLayout_25.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22.addWidget(self.verticalFrame_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ggdsgsd = QtWidgets.QFrame(self.vert)
        self.ggdsgsd.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.ggdsgsd.setObjectName("ggdsgsd")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ggdsgsd)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comBox_Current_Imgae_1Dcode = QtWidgets.QComboBox(self.ggdsgsd)
        self.comBox_Current_Imgae_1Dcode.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.comBox_Current_Imgae_1Dcode.setObjectName("comBox_Current_Imgae_1Dcode")
        self.comBox_Current_Imgae_1Dcode.addItem("")
        self.horizontalLayout_4.addWidget(self.comBox_Current_Imgae_1Dcode)
        self.btn_Live_1Dcode = QtWidgets.QPushButton(self.ggdsgsd)
        self.btn_Live_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.btn_Live_1Dcode.setObjectName("btn_Live_1Dcode")
        self.horizontalLayout_4.addWidget(self.btn_Live_1Dcode)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(3)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.btn_RoomIn_1Dcode = QtWidgets.QPushButton(self.ggdsgsd)
        self.btn_RoomIn_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.btn_RoomIn_1Dcode.setText("")
        self.btn_RoomIn_1Dcode.setObjectName("btn_RoomIn_1Dcode")
        self.horizontalLayout_25.addWidget(self.btn_RoomIn_1Dcode)
        self.btn_RoomOut_1Dcode = QtWidgets.QPushButton(self.ggdsgsd)
        self.btn_RoomOut_1Dcode.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.btn_RoomOut_1Dcode.setText("")
        self.btn_RoomOut_1Dcode.setObjectName("btn_RoomOut_1Dcode")
        self.horizontalLayout_25.addWidget(self.btn_RoomOut_1Dcode)
        self.btn_Full_1Dcode = QtWidgets.QPushButton(self.ggdsgsd)
        self.btn_Full_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.btn_Full_1Dcode.setText("")
        self.btn_Full_1Dcode.setObjectName("btn_Full_1Dcode")
        self.horizontalLayout_25.addWidget(self.btn_Full_1Dcode)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_25)
        self.spinBox_Percent_1Dcode = QtWidgets.QSpinBox(self.ggdsgsd)
        self.spinBox_Percent_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.spinBox_Percent_1Dcode.setMinimum(1)
        self.spinBox_Percent_1Dcode.setMaximum(1000)
        self.spinBox_Percent_1Dcode.setObjectName("spinBox_Percent_1Dcode")
        self.horizontalLayout_24.addWidget(self.spinBox_Percent_1Dcode)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_24)
        self.verticalLayout_3.addWidget(self.ggdsgsd)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scroll_ShowImgae_1Dcode = QtWidgets.QScrollArea(self.vert)
        self.scroll_ShowImgae_1Dcode.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.scroll_ShowImgae_1Dcode.setWidgetResizable(True)
        self.scroll_ShowImgae_1Dcode.setObjectName("scroll_ShowImgae_1Dcode")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 574, 649))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")

        #####################################3
        #self.lab_showImage = QtWidgets.QLabel(self.frame_7)
        self.lab_showImage = MyLabel(self.frame_7)

        ###############################################
        self.lab_showImage.setText("")
        self.lab_showImage.setObjectName("lab_showImage")
        self.verticalLayout_27.addWidget(self.lab_showImage)

        self.verticalLayout_30.addLayout(self.verticalLayout_27)
        self.verticalLayout_33.addWidget(self.frame_7)
        self.scroll_ShowImgae_1Dcode.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scroll_ShowImgae_1Dcode)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.vert)
        self.frame_3.setStyleSheet("background-color: rgb(32, 74, 135);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_11.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox.setStyleSheet("background-color: rgb(32, 74, 135);\n"
"\n"
"color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_4 = QtWidgets.QFrame(self.groupBox)
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalFrame1 = QtWidgets.QFrame(self.frame_4)
        self.verticalFrame1.setStyleSheet("background-color: rgb(32, 74, 135);")
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.verticalFrame1)
        self.label.setStyleSheet("background-color: rgb(32, 74, 135);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(20, -1, 10, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.verticalFrame1)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btn_ReferenceImage_1Dcode = QtWidgets.QPushButton(self.verticalFrame1)
        self.btn_ReferenceImage_1Dcode.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.btn_ReferenceImage_1Dcode.setObjectName("btn_ReferenceImage_1Dcode")
        self.horizontalLayout_5.addWidget(self.btn_ReferenceImage_1Dcode)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_15.addWidget(self.verticalFrame1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_4)
        self.scrollArea_2.setEnabled(True)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 536, 573))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_5.setMinimumSize(QtCore.QSize(400, 500))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setContentsMargins(-1, 0, -1, 10)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalFrame_5 = QtWidgets.QFrame(self.frame_5)
        self.horizontalFrame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.horizontalFrame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame_5.setObjectName("horizontalFrame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalFrame_5)
        self.horizontalLayout_8.setContentsMargins(10, -1, 10, 5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.horizontalFrame_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.btn_DetectionCondition_1Dcode = QtWidgets.QPushButton(self.horizontalFrame_5)
        self.btn_DetectionCondition_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_DetectionCondition_1Dcode.setObjectName("btn_DetectionCondition_1Dcode")
        self.horizontalLayout_8.addWidget(self.btn_DetectionCondition_1Dcode)
        self.verticalLayout_24.addWidget(self.horizontalFrame_5)
        self.verticalFrame_19 = QtWidgets.QFrame(self.frame_5)
        self.verticalFrame_19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.verticalFrame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_19.setObjectName("verticalFrame_19")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.verticalFrame_19)
        self.verticalLayout_26.setContentsMargins(-1, 10, -1, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.verticalFrame_19)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.comBox_CodeType_1Dcode = QtWidgets.QComboBox(self.verticalFrame_19)
        self.comBox_CodeType_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.comBox_CodeType_1Dcode.setObjectName("comBox_CodeType_1Dcode")
        self.comBox_CodeType_1Dcode.addItem("")
        self.comBox_CodeType_1Dcode.addItem("")
        self.comBox_CodeType_1Dcode.addItem("")
        self.comBox_CodeType_1Dcode.addItem("")
        self.comBox_CodeType_1Dcode.addItem("")
        self.comBox_CodeType_1Dcode.addItem("")
        self.comBox_CodeType_1Dcode.addItem("")
        self.comBox_CodeType_1Dcode.addItem("")
        self.comBox_CodeType_1Dcode.addItem("")
        self.horizontalLayout_10.addWidget(self.comBox_CodeType_1Dcode)
        self.verticalLayout_26.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(20, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.btn_AutoTurning_1Dcode = QtWidgets.QPushButton(self.verticalFrame_19)
        self.btn_AutoTurning_1Dcode.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_AutoTurning_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_AutoTurning_1Dcode.setObjectName("btn_AutoTurning_1Dcode")
        self.horizontalLayout_9.addWidget(self.btn_AutoTurning_1Dcode)
        self.verticalLayout_26.addLayout(self.horizontalLayout_9)
        self.horizontalFrame_8 = QtWidgets.QFrame(self.verticalFrame_19)
        self.horizontalFrame_8.setObjectName("horizontalFrame_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalFrame_8)
        self.horizontalLayout_11.setContentsMargins(20, 0, 0, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.horizontalFrame_8)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.lab_CodeResolution_1Dcode = QtWidgets.QLabel(self.horizontalFrame_8)
        self.lab_CodeResolution_1Dcode.setMinimumSize(QtCore.QSize(50, 25))
        self.lab_CodeResolution_1Dcode.setFrameShape(QtWidgets.QFrame.Box)
        self.lab_CodeResolution_1Dcode.setText("")
        self.lab_CodeResolution_1Dcode.setObjectName("lab_CodeResolution_1Dcode")
        self.horizontalLayout_11.addWidget(self.lab_CodeResolution_1Dcode)
        self.label_8 = QtWidgets.QLabel(self.horizontalFrame_8)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.verticalLayout_26.addWidget(self.horizontalFrame_8)
        self.verticalLayout_24.addWidget(self.verticalFrame_19)
        self.verticalLayout_19.addLayout(self.verticalLayout_24)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalFrame_9 = QtWidgets.QFrame(self.frame_5)
        self.horizontalFrame_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.horizontalFrame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame_9.setObjectName("horizontalFrame_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalFrame_9)
        self.horizontalLayout_12.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.horizontalFrame_9)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.btn_ReadDataSetting_1Dcode = QtWidgets.QPushButton(self.horizontalFrame_9)
        self.btn_ReadDataSetting_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_ReadDataSetting_1Dcode.setObjectName("btn_ReadDataSetting_1Dcode")
        self.horizontalLayout_12.addWidget(self.btn_ReadDataSetting_1Dcode)
        self.verticalLayout_22.addWidget(self.horizontalFrame_9)
        self.verticalFrame_20 = QtWidgets.QFrame(self.frame_5)
        self.verticalFrame_20.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.verticalFrame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_20.setObjectName("verticalFrame_20")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.verticalFrame_20)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_12 = QtWidgets.QLabel(self.verticalFrame_20)
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_29.addWidget(self.label_12)
        self.verticalLayout_28.addLayout(self.verticalLayout_29)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lab_ReadData_1Dcode = QtWidgets.QLabel(self.verticalFrame_20)
        self.lab_ReadData_1Dcode.setMinimumSize(QtCore.QSize(300, 0))
        self.lab_ReadData_1Dcode.setFrameShape(QtWidgets.QFrame.Box)
        self.lab_ReadData_1Dcode.setText("")
        self.lab_ReadData_1Dcode.setObjectName("lab_ReadData_1Dcode")
        self.horizontalLayout_14.addWidget(self.lab_ReadData_1Dcode)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.btn_ReadDataDetail_1Dcode = QtWidgets.QPushButton(self.verticalFrame_20)
        self.btn_ReadDataDetail_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_ReadDataDetail_1Dcode.setObjectName("btn_ReadDataDetail_1Dcode")
        self.horizontalLayout_14.addWidget(self.btn_ReadDataDetail_1Dcode)
        self.verticalLayout_28.addLayout(self.horizontalLayout_14)
        self.verticalLayout_22.addWidget(self.verticalFrame_20)
        self.verticalLayout_19.addLayout(self.verticalLayout_22)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.horizontalFrame_11 = QtWidgets.QFrame(self.frame_6)
        self.horizontalFrame_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.horizontalFrame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame_11.setObjectName("horizontalFrame_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalFrame_11)
        self.horizontalLayout_15.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.horizontalFrame_11)
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.btn_Verification_1Dcode = QtWidgets.QPushButton(self.horizontalFrame_11)
        self.btn_Verification_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_Verification_1Dcode.setObjectName("btn_Verification_1Dcode")
        self.horizontalLayout_15.addWidget(self.btn_Verification_1Dcode)
        self.verticalLayout_32.addWidget(self.horizontalFrame_11)
        self.horizontalFrame_51 = QtWidgets.QFrame(self.frame_6)
        self.horizontalFrame_51.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.horizontalFrame_51.setObjectName("horizontalFrame_51")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalFrame_51)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_14 = QtWidgets.QLabel(self.horizontalFrame_51)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_21.addWidget(self.label_14)
        self.verticalLayout_32.addWidget(self.horizontalFrame_51)
        self.verticalFrame2 = QtWidgets.QFrame(self.frame_6)
        self.verticalFrame2.setMinimumSize(QtCore.QSize(0, 50))
        self.verticalFrame2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_32.addWidget(self.verticalFrame2)
        self.verticalLayout_23.addLayout(self.verticalLayout_32)
        self.verticalLayout_19.addWidget(self.frame_6)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalFrame_12 = QtWidgets.QFrame(self.frame_5)
        self.horizontalFrame_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.horizontalFrame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame_12.setObjectName("horizontalFrame_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalFrame_12)
        self.horizontalLayout_16.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.horizontalFrame_12)
        self.label_16.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.btn_JudgmentConditions_1Dcode = QtWidgets.QPushButton(self.horizontalFrame_12)
        self.btn_JudgmentConditions_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_JudgmentConditions_1Dcode.setObjectName("btn_JudgmentConditions_1Dcode")
        self.horizontalLayout_16.addWidget(self.btn_JudgmentConditions_1Dcode)
        self.verticalLayout_21.addWidget(self.horizontalFrame_12)
        self.verticalFrame_24 = QtWidgets.QFrame(self.frame_5)
        self.verticalFrame_24.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.verticalFrame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.verticalFrame_24.setObjectName("verticalFrame_24")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.verticalFrame_24)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.frame1 = QtWidgets.QFrame(self.verticalFrame_24)
        self.frame1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame1.setObjectName("frame1")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout_19.setContentsMargins(30, -1, 10, 2)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_17 = QtWidgets.QLabel(self.frame1)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        self.btn_CopyReadData_1Dcode = QtWidgets.QPushButton(self.frame1)
        self.btn_CopyReadData_1Dcode.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_CopyReadData_1Dcode.setObjectName("btn_CopyReadData_1Dcode")
        self.horizontalLayout_19.addWidget(self.btn_CopyReadData_1Dcode)
        self.verticalLayout_31.addWidget(self.frame1)
        self.frame2 = QtWidgets.QFrame(self.verticalFrame_24)
        self.frame2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_20.setContentsMargins(30, -1, 10, 2)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tedit_CopyReadData_1Dcode = QtWidgets.QTextEdit(self.frame2)
        self.tedit_CopyReadData_1Dcode.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tedit_CopyReadData_1Dcode.setObjectName("tedit_CopyReadData_1Dcode")
        self.horizontalLayout_20.addWidget(self.tedit_CopyReadData_1Dcode)
        self.verticalLayout_31.addWidget(self.frame2)
        self.verticalLayout_21.addWidget(self.verticalFrame_24)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(30, -1, -1, -1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        self.label_19.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_27.addWidget(self.label_19)
        self.verticalLayout_21.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(30, 0, 10, 4)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.ledit_CovertedData_1Dcode = QtWidgets.QLineEdit(self.frame_5)
        self.ledit_CovertedData_1Dcode.setMinimumSize(QtCore.QSize(300, 0))
        self.ledit_CovertedData_1Dcode.setObjectName("ledit_CovertedData_1Dcode")
        self.horizontalLayout_30.addWidget(self.ledit_CovertedData_1Dcode)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem9)
        self.btn_ConvertedData_1Dcode = QtWidgets.QPushButton(self.frame_5)
        self.btn_ConvertedData_1Dcode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_ConvertedData_1Dcode.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.btn_ConvertedData_1Dcode.setObjectName("btn_ConvertedData_1Dcode")
        self.horizontalLayout_30.addWidget(self.btn_ConvertedData_1Dcode)
        self.verticalLayout_21.addLayout(self.horizontalLayout_30)
        self.verticalLayout_19.addLayout(self.verticalLayout_21)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        self.verticalLayout_18.addWidget(self.frame_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_18)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_17.addWidget(self.scrollArea_2)
        self.verticalLayout_15.addLayout(self.verticalLayout_17)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.verticalLayout_12.addWidget(self.frame_4)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_14.addWidget(self.groupBox)
        self.verticalLayout_10.addLayout(self.verticalLayout_14)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 5)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_Display_1Dcode = QtWidgets.QPushButton(self.frame_3)
        self.btn_Display_1Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Display_1Dcode.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_Display_1Dcode.setObjectName("btn_Display_1Dcode")
        self.horizontalLayout_3.addWidget(self.btn_Display_1Dcode)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.btn_OK_1Dcode = QtWidgets.QPushButton(self.frame_3)
        self.btn_OK_1Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_OK_1Dcode.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_OK_1Dcode.setObjectName("btn_OK_1Dcode")
        self.horizontalLayout_3.addWidget(self.btn_OK_1Dcode)
        self.btn_Cancel_1Dcode = QtWidgets.QPushButton(self.frame_3)
        self.btn_Cancel_1Dcode.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Cancel_1Dcode.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_Cancel_1Dcode.setObjectName("btn_Cancel_1Dcode")
        self.horizontalLayout_3.addWidget(self.btn_Cancel_1Dcode)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_9.addWidget(self.frame_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.frae = QtWidgets.QFrame(self.vert)
        self.frae.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.frae.setObjectName("frae")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frae)
        self.horizontalLayout_7.setContentsMargins(2, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.frae)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btn_RegisterImage_1Dcode = QtWidgets.QPushButton(self.frame_2)
        self.btn_RegisterImage_1Dcode.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_RegisterImage_1Dcode.setMaximumSize(QtCore.QSize(150, 60))
        self.btn_RegisterImage_1Dcode.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.btn_RegisterImage_1Dcode.setObjectName("btn_RegisterImage_1Dcode")
        self.horizontalLayout_17.addWidget(self.btn_RegisterImage_1Dcode)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.btn_Run_1Dcode = QtWidgets.QPushButton(self.frame_2)
        self.btn_Run_1Dcode.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_Run_1Dcode.setMaximumSize(QtCore.QSize(100, 60))
        self.btn_Run_1Dcode.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"color: rgb(238, 238, 236);")
        self.btn_Run_1Dcode.setObjectName("btn_Run_1Dcode")
        self.horizontalLayout_17.addWidget(self.btn_Run_1Dcode)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem12)
        self.btn_Running_1Dcode = QtWidgets.QPushButton(self.frame_2)
        self.btn_Running_1Dcode.setMaximumSize(QtCore.QSize(100, 60))
        self.btn_Running_1Dcode.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"color: rgb(238, 238, 236);")
        self.btn_Running_1Dcode.setObjectName("btn_Running_1Dcode")
        self.horizontalLayout_17.addWidget(self.btn_Running_1Dcode)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_7.addWidget(self.frame_2)
        self.verticalLayout_8.addWidget(self.frae)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2.addWidget(self.vert)

        self.retranslateUi(Ui_Class_1Dcode)
        QtCore.QMetaObject.connectSlotsByName(Ui_Class_1Dcode)

    def retranslateUi(self, Ui_Class_1Dcode):
        _translate = QtCore.QCoreApplication.translate
        Ui_Class_1Dcode.setWindowTitle(_translate("Ui_Class_1Dcode", "Dialog"))
        self.btn_LelfCommand_1Dcode.setText(_translate("Ui_Class_1Dcode", "<-"))
        self.btn_RightCommand_1Dcode.setText(_translate("Ui_Class_1Dcode", "->"))
        self.comBox_Current_Imgae_1Dcode.setItemText(0, _translate("Ui_Class_1Dcode", "Current Image"))
        self.btn_Live_1Dcode.setText(_translate("Ui_Class_1Dcode", "Live"))
        self.groupBox.setTitle(_translate("Ui_Class_1Dcode", "1D Code Reader"))
        self.label.setText(_translate("Ui_Class_1Dcode", "1D Code Reader"))
        self.label_2.setText(_translate("Ui_Class_1Dcode", "Reference Image"))
        self.btn_ReferenceImage_1Dcode.setText(_translate("Ui_Class_1Dcode", "1-00"))
        self.label_6.setText(_translate("Ui_Class_1Dcode", "*Detection Condititons "))
        self.btn_DetectionCondition_1Dcode.setText(_translate("Ui_Class_1Dcode", ">>>"))
        self.label_7.setText(_translate("Ui_Class_1Dcode", "Code  Type"))

        self.comBox_CodeType_1Dcode.setItemText(0, _translate("Ui_Class_1Dcode", "Not Specified"))
        self.comBox_CodeType_1Dcode.setItemText(1, _translate("Ui_Class_1Dcode", "CODE39"))
        self.comBox_CodeType_1Dcode.setItemText(2, _translate("Ui_Class_1Dcode", "CODE128"))
        self.comBox_CodeType_1Dcode.setItemText(3, _translate("Ui_Class_1Dcode", "EAN/JAN/UPC"))
        self.comBox_CodeType_1Dcode.setItemText(4, _translate("Ui_Class_1Dcode", "GS1 Databar"))
        self.comBox_CodeType_1Dcode.setItemText(5, _translate("Ui_Class_1Dcode", "ITF"))
        self.comBox_CodeType_1Dcode.setItemText(6, _translate("Ui_Class_1Dcode", "Codabar/NW- 7"))
        self.comBox_CodeType_1Dcode.setItemText(7, _translate("Ui_Class_1Dcode", "pHARMACODE"))
        self.comBox_CodeType_1Dcode.setItemText(8, _translate("Ui_Class_1Dcode", "CODE93"))

        self.btn_AutoTurning_1Dcode.setText(_translate("Ui_Class_1Dcode", "Auto Turning"))
        self.label_10.setText(_translate("Ui_Class_1Dcode", "Code  Resolution   "))
        self.label_8.setText(_translate("Ui_Class_1Dcode", " pixel"))
        self.label_11.setText(_translate("Ui_Class_1Dcode", "* Read Data Setting            "))
        self.btn_ReadDataSetting_1Dcode.setText(_translate("Ui_Class_1Dcode", ">>>"))
        self.label_12.setText(_translate("Ui_Class_1Dcode", "     Read data "))
        self.btn_ReadDataDetail_1Dcode.setText(_translate("Ui_Class_1Dcode", ">>>"))
        self.label_15.setText(_translate("Ui_Class_1Dcode", "*Verification"))
        self.btn_Verification_1Dcode.setText(_translate("Ui_Class_1Dcode", ">>>"))
        self.label_14.setText(_translate("Ui_Class_1Dcode", "           Verification                      "))
        self.label_16.setText(_translate("Ui_Class_1Dcode", "*Judgment Conditions"))
        self.btn_JudgmentConditions_1Dcode.setText(_translate("Ui_Class_1Dcode", ">>>"))
        self.label_17.setText(_translate("Ui_Class_1Dcode", "Reference Pattern "))
        self.btn_CopyReadData_1Dcode.setText(_translate("Ui_Class_1Dcode", "Copy  from Read Data"))
        self.label_19.setText(_translate("Ui_Class_1Dcode", "(Converted)"))
        self.btn_ConvertedData_1Dcode.setText(_translate("Ui_Class_1Dcode", ">>>"))
        self.btn_Display_1Dcode.setText(_translate("Ui_Class_1Dcode", "Display"))
        self.btn_OK_1Dcode.setText(_translate("Ui_Class_1Dcode", "OK"))
        self.btn_Cancel_1Dcode.setText(_translate("Ui_Class_1Dcode", "Cancel"))
        self.btn_RegisterImage_1Dcode.setText(_translate("Ui_Class_1Dcode", "Register Image"))
        self.btn_Run_1Dcode.setText(_translate("Ui_Class_1Dcode", "Run"))
        self.btn_Running_1Dcode.setText(_translate("Ui_Class_1Dcode", "Running"))
