# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I_DlogAddTool.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Class_DlogAddTool(object):
    def setupUi(self, Class_DlogAddTool):
        Class_DlogAddTool.setObjectName("Class_DlogAddTool")
        Class_DlogAddTool.resize(1216, 825)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Class_DlogAddTool)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalFrame = QtWidgets.QFrame(Class_DlogAddTool)
        self.verticalFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QtWidgets.QLabel(self.verticalFrame)
        self.label.setStyleSheet("background-color: rgb(32, 74, 135);\n"
"color: rgb(238, 238, 236);")
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.verticalLayout.addWidget(self.verticalFrame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(Class_DlogAddTool)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 2000))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -9, 1218, 118))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalFrame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.horizontalFrame_3.setMinimumSize(QtCore.QSize(1200, 0))
        self.horizontalFrame_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(30)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_Idetification_AddTool = QtWidgets.QPushButton(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Idetification_AddTool.sizePolicy().hasHeightForWidth())
        self.btn_Idetification_AddTool.setSizePolicy(sizePolicy)
        self.btn_Idetification_AddTool.setMinimumSize(QtCore.QSize(150, 100))
        self.btn_Idetification_AddTool.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_Idetification_AddTool.setObjectName("btn_Idetification_AddTool")
        self.horizontalLayout_6.addWidget(self.btn_Idetification_AddTool, 0, QtCore.Qt.AlignHCenter)
        self.btn_count_AddTool = QtWidgets.QPushButton(self.horizontalFrame_3)
        self.btn_count_AddTool.setMinimumSize(QtCore.QSize(150, 100))
        self.btn_count_AddTool.setObjectName("btn_count_AddTool")
        self.horizontalLayout_6.addWidget(self.btn_count_AddTool)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_18.addWidget(self.horizontalFrame_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_12.addWidget(self.scrollArea)
        self.verticalLayout_8.addLayout(self.verticalLayout_12)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(-60, 0, 1218, 105))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalFrame_31 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.horizontalFrame_31.setMinimumSize(QtCore.QSize(1200, 0))
        self.horizontalFrame_31.setMaximumSize(QtCore.QSize(16777215, 200))
        self.horizontalFrame_31.setObjectName("horizontalFrame_31")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalFrame_31)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_20.addWidget(self.horizontalFrame_31)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_10.addWidget(self.scrollArea_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(Class_DlogAddTool)
        self.groupBox_2.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, -14, 1218, 136))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_defind1_AddTool = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.frame_defind1_AddTool.setMinimumSize(QtCore.QSize(1200, 0))
        self.frame_defind1_AddTool.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_defind1_AddTool.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_defind1_AddTool.setObjectName("frame_defind1_AddTool")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_defind1_AddTool)
        self.horizontalLayout_5.setSpacing(30)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_Character_AddTool = QtWidgets.QPushButton(self.frame_defind1_AddTool)
        self.btn_Character_AddTool.setMinimumSize(QtCore.QSize(150, 100))
        self.btn_Character_AddTool.setObjectName("btn_Character_AddTool")
        self.horizontalLayout_5.addWidget(self.btn_Character_AddTool)
        self.btn_1Dcode_AddTool = QtWidgets.QPushButton(self.frame_defind1_AddTool)
        self.btn_1Dcode_AddTool.setMinimumSize(QtCore.QSize(150, 100))
        self.btn_1Dcode_AddTool.setObjectName("btn_1Dcode_AddTool")
        self.horizontalLayout_5.addWidget(self.btn_1Dcode_AddTool)
        self.btn_2Dcode_AddTool = QtWidgets.QPushButton(self.frame_defind1_AddTool)
        self.btn_2Dcode_AddTool.setMinimumSize(QtCore.QSize(150, 100))
        self.btn_2Dcode_AddTool.setObjectName("btn_2Dcode_AddTool")
        self.horizontalLayout_5.addWidget(self.btn_2Dcode_AddTool)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_8.addWidget(self.frame_defind1_AddTool)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_16.addWidget(self.scrollArea_4)
        self.verticalLayout_13.addLayout(self.verticalLayout_16)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(-440, 0, 1218, 87))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_defind2_AddTool = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_defind2_AddTool.setMinimumSize(QtCore.QSize(1200, 0))
        self.frame_defind2_AddTool.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_defind2_AddTool.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_defind2_AddTool.setObjectName("frame_defind2_AddTool")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_defind2_AddTool)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_10.addWidget(self.frame_defind2_AddTool)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_15.addWidget(self.scrollArea_3)
        self.verticalLayout_13.addLayout(self.verticalLayout_15)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalFrame_4 = QtWidgets.QFrame(Class_DlogAddTool)
        self.verticalFrame_4.setMinimumSize(QtCore.QSize(300, 0))
        self.verticalFrame_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.verticalFrame_4.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);")
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_4 = QtWidgets.QLabel(self.verticalFrame_4)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_17.addWidget(self.label_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_17)
        self.label_5 = QtWidgets.QLabel(self.verticalFrame_4)
        self.label_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.txtb_defind_AddTool = QtWidgets.QTextBrowser(self.verticalFrame_4)
        self.txtb_defind_AddTool.setObjectName("txtb_defind_AddTool")
        self.verticalLayout_19.addWidget(self.txtb_defind_AddTool)
        self.verticalLayout_5.addLayout(self.verticalLayout_19)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_6 = QtWidgets.QLabel(self.verticalFrame_4)
        self.label_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_21.addWidget(self.label_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_21)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.verticalFrame_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalWidget_2 = QtWidgets.QWidget(Class_DlogAddTool)
        self.horizontalWidget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.tedit_IDTool_AddTool = QtWidgets.QTextEdit(self.horizontalWidget_2)
        self.tedit_IDTool_AddTool.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tedit_IDTool_AddTool.setObjectName("tedit_IDTool_AddTool")
        self.horizontalLayout_2.addWidget(self.tedit_IDTool_AddTool)
        self.verticalLayout.addWidget(self.horizontalWidget_2)
        self.horizontalFrame_32 = QtWidgets.QFrame(Class_DlogAddTool)
        self.horizontalFrame_32.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalFrame_32.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame_32.setObjectName("horizontalFrame_32")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame_32)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txtb_noteTool_AddTool = QtWidgets.QTextBrowser(self.horizontalFrame_32)
        self.txtb_noteTool_AddTool.setObjectName("txtb_noteTool_AddTool")
        self.verticalLayout_3.addWidget(self.txtb_noteTool_AddTool)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.btn_Add_AddTool = QtWidgets.QPushButton(self.horizontalFrame_32)
        self.btn_Add_AddTool.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 87, 83);")
        self.btn_Add_AddTool.setObjectName("btn_Add_AddTool")
        self.horizontalLayout_4.addWidget(self.btn_Add_AddTool)
        self.btn_Cancel_AddTool = QtWidgets.QPushButton(self.horizontalFrame_32)
        self.btn_Cancel_AddTool.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);")
        self.btn_Cancel_AddTool.setObjectName("btn_Cancel_AddTool")
        self.horizontalLayout_4.addWidget(self.btn_Cancel_AddTool)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.horizontalFrame_32)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Class_DlogAddTool)
        QtCore.QMetaObject.connectSlotsByName(Class_DlogAddTool)

    def retranslateUi(self, Class_DlogAddTool):
        _translate = QtCore.QCoreApplication.translate
        Class_DlogAddTool.setWindowTitle(_translate("Class_DlogAddTool", "Dialog"))
        self.label.setText(_translate("Class_DlogAddTool", "<html><head/><body><p><span style=\" font-size:20pt;\">Tool Catalog</span></p></body></html>"))
        self.groupBox.setTitle(_translate("Class_DlogAddTool", "Category"))
        self.btn_Idetification_AddTool.setText(_translate("Class_DlogAddTool", "Identification"))
        self.btn_count_AddTool.setText(_translate("Class_DlogAddTool", "Count"))
        self.groupBox_2.setTitle(_translate("Class_DlogAddTool", "Which target type should be identified ?"))
        self.btn_Character_AddTool.setText(_translate("Class_DlogAddTool", "Character"))
        self.btn_1Dcode_AddTool.setText(_translate("Class_DlogAddTool", "1D Code"))
        self.btn_2Dcode_AddTool.setText(_translate("Class_DlogAddTool", "2D code"))
        self.label_4.setText(_translate("Class_DlogAddTool", "<html><head/><body><p><span style=\" font-size:20pt;\">Identification</span></p></body></html>"))
        self.txtb_defind_AddTool.setHtml(_translate("Class_DlogAddTool", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">This is the category of tools which identify the text /barcode information on a taget object to analyze or output it  as a  character string</span></p></body></html>"))
        self.label_3.setText(_translate("Class_DlogAddTool", "ID tool"))
        self.txtb_noteTool_AddTool.setHtml(_translate("Class_DlogAddTool", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">When the variation in thr position of the object affects the result of the tools ,use the position adjustment tools</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_Add_AddTool.setText(_translate("Class_DlogAddTool", "Add"))
        self.btn_Cancel_AddTool.setText(_translate("Class_DlogAddTool", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Class_DlogAddTool = QtWidgets.QDialog()
    ui = Ui_Class_DlogAddTool()
    ui.setupUi(Class_DlogAddTool)
    Class_DlogAddTool.show()
    sys.exit(app.exec_())

