# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I_CameraSetting.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Class_CameraSetting(object):
    def setupUi(self, Class_CameraSetting):
        Class_CameraSetting.setObjectName("Class_CameraSetting")
        Class_CameraSetting.resize(1164, 820)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Class_CameraSetting)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vert = QtWidgets.QFrame(Class_CameraSetting)
        self.vert.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.vert.setObjectName("vert")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.vert)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.vert)
        self.frame.setMinimumSize(QtCore.QSize(150, 200))
        self.frame.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_22.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_22.setSpacing(10)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_text1 = QtWidgets.QFrame(self.frame)
        self.frame_text1.setStyleSheet("color: rgb(238, 238, 236);")
        self.frame_text1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_text1.setObjectName("frame_text1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_text1)
        self.verticalLayout_4.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hori_tex1lab1 = QtWidgets.QHBoxLayout()
        self.hori_tex1lab1.setObjectName("hori_tex1lab1")
        self.lab_InforLine1 = QtWidgets.QLabel(self.frame_text1)
        self.lab_InforLine1.setObjectName("lab_InforLine1")
        self.hori_tex1lab1.addWidget(self.lab_InforLine1)
        self.verticalLayout_4.addLayout(self.hori_tex1lab1)
        self.hori_tex1lab2 = QtWidgets.QHBoxLayout()
        self.hori_tex1lab2.setObjectName("hori_tex1lab2")
        self.lab_InforLine2 = QtWidgets.QLabel(self.frame_text1)
        self.lab_InforLine2.setObjectName("lab_InforLine2")
        self.hori_tex1lab2.addWidget(self.lab_InforLine2)
        self.verticalLayout_4.addLayout(self.hori_tex1lab2)
        self.hori_tex1lab3 = QtWidgets.QHBoxLayout()
        self.hori_tex1lab3.setObjectName("hori_tex1lab3")
        self.lab_InforLine3 = QtWidgets.QLabel(self.frame_text1)
        self.lab_InforLine3.setObjectName("lab_InforLine3")
        self.hori_tex1lab3.addWidget(self.lab_InforLine3)
        self.verticalLayout_4.addLayout(self.hori_tex1lab3)
        self.hori_tex1lab4 = QtWidgets.QHBoxLayout()
        self.hori_tex1lab4.setObjectName("hori_tex1lab4")
        self.lab_InforLine4 = QtWidgets.QLabel(self.frame_text1)
        self.lab_InforLine4.setText("")
        self.lab_InforLine4.setObjectName("lab_InforLine4")
        self.hori_tex1lab4.addWidget(self.lab_InforLine4)
        self.verticalLayout_4.addLayout(self.hori_tex1lab4)
        self.hori_tex1lab5 = QtWidgets.QHBoxLayout()
        self.hori_tex1lab5.setObjectName("hori_tex1lab5")
        self.lab_InforLine5 = QtWidgets.QLabel(self.frame_text1)
        self.lab_InforLine5.setText("")
        self.lab_InforLine5.setObjectName("lab_InforLine5")
        self.hori_tex1lab5.addWidget(self.lab_InforLine5)
        self.verticalLayout_4.addLayout(self.hori_tex1lab5)
        self.hori_tex1lab6 = QtWidgets.QHBoxLayout()
        self.hori_tex1lab6.setObjectName("hori_tex1lab6")
        self.lab_InforLine6 = QtWidgets.QLabel(self.frame_text1)
        self.lab_InforLine6.setText("")
        self.lab_InforLine6.setObjectName("lab_InforLine6")
        self.hori_tex1lab6.addWidget(self.lab_InforLine6)
        self.verticalLayout_4.addLayout(self.hori_tex1lab6)
        self.horizontalLayout_13.addWidget(self.frame_text1)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_13)
        self.verticalFrame_2 = QtWidgets.QFrame(self.frame)
        self.verticalFrame_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_25.addItem(spacerItem)
        self.spinBox_Paper = QtWidgets.QSpinBox(self.verticalFrame_2)
        self.spinBox_Paper.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.spinBox_Paper.setObjectName("spinBox_Paper")
        self.verticalLayout_25.addWidget(self.spinBox_Paper)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btn_LelfCommand = QtWidgets.QPushButton(self.verticalFrame_2)
        self.btn_LelfCommand.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_LelfCommand.setObjectName("btn_LelfCommand")
        self.horizontalLayout_23.addWidget(self.btn_LelfCommand)
        self.btn_RightCommand = QtWidgets.QPushButton(self.verticalFrame_2)
        self.btn_RightCommand.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.btn_RightCommand.setObjectName("btn_RightCommand")
        self.horizontalLayout_23.addWidget(self.btn_RightCommand)
        self.verticalLayout_25.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22.addWidget(self.verticalFrame_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ggdsgsd = QtWidgets.QFrame(self.vert)
        self.ggdsgsd.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.ggdsgsd.setObjectName("ggdsgsd")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ggdsgsd)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comBox_Current_Image = QtWidgets.QComboBox(self.ggdsgsd)
        self.comBox_Current_Image.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.comBox_Current_Image.setObjectName("comBox_Current_Image")
        self.comBox_Current_Image.addItem("")
        self.horizontalLayout_4.addWidget(self.comBox_Current_Image)
        self.btn_Live = QtWidgets.QPushButton(self.ggdsgsd)
        self.btn_Live.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.btn_Live.setObjectName("btn_Live")
        self.horizontalLayout_4.addWidget(self.btn_Live)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(3)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.btn_ZoomIn = QtWidgets.QPushButton(self.ggdsgsd)
        self.btn_ZoomIn.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.btn_ZoomIn.setText("")
        self.btn_ZoomIn.setObjectName("btn_ZoomIn")
        self.horizontalLayout_25.addWidget(self.btn_ZoomIn)
        self.btn_ZoomOut = QtWidgets.QPushButton(self.ggdsgsd)
        self.btn_ZoomOut.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.btn_ZoomOut.setText("")
        self.btn_ZoomOut.setObjectName("btn_ZoomOut")
        self.horizontalLayout_25.addWidget(self.btn_ZoomOut)
        self.btn_ZoomNormal = QtWidgets.QPushButton(self.ggdsgsd)
        self.btn_ZoomNormal.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.btn_ZoomNormal.setText("")
        self.btn_ZoomNormal.setObjectName("btn_ZoomNormal")
        self.horizontalLayout_25.addWidget(self.btn_ZoomNormal)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_25)
        self.spinBox_Percent = QtWidgets.QSpinBox(self.ggdsgsd)
        self.spinBox_Percent.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.spinBox_Percent.setMinimum(1)
        self.spinBox_Percent.setMaximum(1000)
        self.spinBox_Percent.setObjectName("spinBox_Percent")
        self.horizontalLayout_24.addWidget(self.spinBox_Percent)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_24)
        self.verticalLayout_3.addWidget(self.ggdsgsd)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scroll_ShowImgae = QtWidgets.QScrollArea(self.vert)
        self.scroll_ShowImgae.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.scroll_ShowImgae.setWidgetResizable(True)
        self.scroll_ShowImgae.setObjectName("scroll_ShowImgae")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 574, 547))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_ShowImgae.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scroll_ShowImgae)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.vert)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lab_TitleTableSetting = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_TitleTableSetting.sizePolicy().hasHeightForWidth())
        self.lab_TitleTableSetting.setSizePolicy(sizePolicy)
        self.lab_TitleTableSetting.setMinimumSize(QtCore.QSize(0, 50))
        self.lab_TitleTableSetting.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lab_TitleTableSetting.setStyleSheet("color: rgb(238, 238, 236);font: 20pt \"Ubuntu\";")
        self.lab_TitleTableSetting.setObjectName("lab_TitleTableSetting")
        self.verticalLayout_5.addWidget(self.lab_TitleTableSetting)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.tabWidget = QtWidgets.QTabWidget(self.vert)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Camera = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tab_Camera.setFont(font)
        self.tab_Camera.setObjectName("tab_Camera")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_Camera)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_Camera)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 556, 539))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setStyleSheet("font: 15pt \"Ubuntu\";")
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.btn_settingCameraExtend = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_settingCameraExtend.sizePolicy().hasHeightForWidth())
        self.btn_settingCameraExtend.setSizePolicy(sizePolicy)
        self.btn_settingCameraExtend.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_settingCameraExtend.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_settingCameraExtend.setFont(font)
        self.btn_settingCameraExtend.setObjectName("btn_settingCameraExtend")
        self.horizontalLayout_3.addWidget(self.btn_settingCameraExtend)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_12.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_17.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_15.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.btn_AutoDetecTypeCamera = QtWidgets.QPushButton(self.frame_7)
        self.btn_AutoDetecTypeCamera.setMinimumSize(QtCore.QSize(80, 30))
        self.btn_AutoDetecTypeCamera.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_AutoDetecTypeCamera.setFont(font)
        self.btn_AutoDetecTypeCamera.setObjectName("btn_AutoDetecTypeCamera")
        self.horizontalLayout_15.addWidget(self.btn_AutoDetecTypeCamera)
        self.verticalLayout_16.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.combox_TypeCamera = QtWidgets.QComboBox(self.frame_7)
        self.combox_TypeCamera.setMinimumSize(QtCore.QSize(300, 30))
        self.combox_TypeCamera.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.combox_TypeCamera.setFont(font)
        self.combox_TypeCamera.setObjectName("combox_TypeCamera")
        self.horizontalLayout_14.addWidget(self.combox_TypeCamera)
        self.verticalLayout_16.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lab_InfoCamera = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_InfoCamera.sizePolicy().hasHeightForWidth())
        self.lab_InfoCamera.setSizePolicy(sizePolicy)
        self.lab_InfoCamera.setMinimumSize(QtCore.QSize(0, 30))
        self.lab_InfoCamera.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lab_InfoCamera.setFont(font)
        self.lab_InfoCamera.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_InfoCamera.setObjectName("lab_InfoCamera")
        self.horizontalLayout_12.addWidget(self.lab_InfoCamera)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.combox_SizeImage = QtWidgets.QComboBox(self.frame_7)
        self.combox_SizeImage.setMinimumSize(QtCore.QSize(300, 30))
        self.combox_SizeImage.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.combox_SizeImage.setFont(font)
        self.combox_SizeImage.setObjectName("combox_SizeImage")
        self.horizontalLayout_11.addWidget(self.combox_SizeImage)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.verticalLayout_16.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.combox_ShutterSpeed = QtWidgets.QComboBox(self.frame_7)
        self.combox_ShutterSpeed.setMinimumSize(QtCore.QSize(160, 30))
        self.combox_ShutterSpeed.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.combox_ShutterSpeed.setFont(font)
        self.combox_ShutterSpeed.setObjectName("combox_ShutterSpeed")
        self.horizontalLayout_9.addWidget(self.combox_ShutterSpeed)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.ledit__showTimeShutterSpeed = QtWidgets.QLineEdit(self.frame_7)
        self.ledit__showTimeShutterSpeed.setMinimumSize(QtCore.QSize(100, 30))
        self.ledit__showTimeShutterSpeed.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ledit__showTimeShutterSpeed.setFont(font)
        self.ledit__showTimeShutterSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.ledit__showTimeShutterSpeed.setObjectName("ledit__showTimeShutterSpeed")
        self.horizontalLayout_9.addWidget(self.ledit__showTimeShutterSpeed)
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setMinimumSize(QtCore.QSize(30, 30))
        self.label_7.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.verticalLayout_16.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.lab_ValueSensitivity = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_ValueSensitivity.sizePolicy().hasHeightForWidth())
        self.lab_ValueSensitivity.setSizePolicy(sizePolicy)
        self.lab_ValueSensitivity.setMinimumSize(QtCore.QSize(120, 30))
        self.lab_ValueSensitivity.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lab_ValueSensitivity.setFont(font)
        self.lab_ValueSensitivity.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_ValueSensitivity.setObjectName("lab_ValueSensitivity")
        self.horizontalLayout_8.addWidget(self.lab_ValueSensitivity)
        self.verticalLayout_16.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.Slider_Sensitivity = QtWidgets.QSlider(self.frame_7)
        self.Slider_Sensitivity.setMinimumSize(QtCore.QSize(300, 30))
        self.Slider_Sensitivity.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Slider_Sensitivity.setFont(font)
        self.Slider_Sensitivity.setMaximum(9)
        self.Slider_Sensitivity.setPageStep(1)
        self.Slider_Sensitivity.setProperty("value", 3)
        self.Slider_Sensitivity.setSliderPosition(3)
        self.Slider_Sensitivity.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Sensitivity.setObjectName("Slider_Sensitivity")
        self.horizontalLayout_6.addWidget(self.Slider_Sensitivity)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.verticalLayout_12.addWidget(self.frame_7)
        self.verticalLayout_14.addLayout(self.verticalLayout_12)
        self.verticalLayout_10.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMaximumSize(QtCore.QSize(10000, 100))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setStyleSheet("font: 15pt \"Ubuntu\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(20, -1, 20, 5)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.cbox_HDR = QtWidgets.QCheckBox(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cbox_HDR.setFont(font)
        self.cbox_HDR.setObjectName("cbox_HDR")
        self.horizontalLayout_19.addWidget(self.cbox_HDR)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.btn_setHDR = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_setHDR.setFont(font)
        self.btn_setHDR.setObjectName("btn_setHDR")
        self.horizontalLayout_19.addWidget(self.btn_setHDR)
        self.verticalLayout_13.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(20, -1, 20, 5)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.cbox_Calibration = QtWidgets.QCheckBox(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cbox_Calibration.setFont(font)
        self.cbox_Calibration.setObjectName("cbox_Calibration")
        self.horizontalLayout_16.addWidget(self.cbox_Calibration)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.btn_setCalibration = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_setCalibration.setFont(font)
        self.btn_setCalibration.setObjectName("btn_setCalibration")
        self.horizontalLayout_16.addWidget(self.btn_setCalibration)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.verticalLayout_10.addWidget(self.frame_6)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_9.addWidget(self.frame_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_Camera, "")
        self.tab_Trigger = QtWidgets.QWidget()
        self.tab_Trigger.setObjectName("tab_Trigger")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_Trigger)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_10 = QtWidgets.QFrame(self.tab_Trigger)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_12.setStyleSheet("font: 15pt \"Ubuntu\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_26.addWidget(self.label_12)
        spacerItem10 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem10)
        self.btn_settingTriggerExtend = QtWidgets.QPushButton(self.frame_11)
        self.btn_settingTriggerExtend.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_settingTriggerExtend.setSizeIncrement(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_settingTriggerExtend.setFont(font)
        self.btn_settingTriggerExtend.setObjectName("btn_settingTriggerExtend")
        self.horizontalLayout_26.addWidget(self.btn_settingTriggerExtend)
        self.verticalLayout_22.addLayout(self.horizontalLayout_26)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_13 = QtWidgets.QLabel(self.frame_11)
        self.label_13.setStyleSheet("font: 13pt \"Ubuntu\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_30.addWidget(self.label_13)
        self.verticalLayout_24.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.rbtn_TriggerModeExternal = QtWidgets.QRadioButton(self.frame_11)
        self.rbtn_TriggerModeExternal.setMinimumSize(QtCore.QSize(0, 30))
        self.rbtn_TriggerModeExternal.setStyleSheet("font: 13pt \"Ubuntu\";")
        self.rbtn_TriggerModeExternal.setObjectName("rbtn_TriggerModeExternal")
        self.horizontalLayout_29.addWidget(self.rbtn_TriggerModeExternal)
        self.verticalLayout_24.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.rbtn_TriggerModeInternal = QtWidgets.QRadioButton(self.frame_11)
        self.rbtn_TriggerModeInternal.setMinimumSize(QtCore.QSize(0, 30))
        self.rbtn_TriggerModeInternal.setStyleSheet("font: 13pt \"Ubuntu\";")
        self.rbtn_TriggerModeInternal.setObjectName("rbtn_TriggerModeInternal")
        self.horizontalLayout_28.addWidget(self.rbtn_TriggerModeInternal)
        spacerItem11 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem11)
        self.ledit_TimeTriggerModeInternal = QtWidgets.QLineEdit(self.frame_11)
        self.ledit_TimeTriggerModeInternal.setMinimumSize(QtCore.QSize(100, 30))
        self.ledit_TimeTriggerModeInternal.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ledit_TimeTriggerModeInternal.setFont(font)
        self.ledit_TimeTriggerModeInternal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ledit_TimeTriggerModeInternal.setObjectName("ledit_TimeTriggerModeInternal")
        self.horizontalLayout_28.addWidget(self.ledit_TimeTriggerModeInternal)
        self.label_14 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_28.addWidget(self.label_14)
        self.verticalLayout_24.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setStyleSheet("font: 13pt \"Ubuntu\";")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_27.addWidget(self.label_15)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem12)
        self.combox_TriggerSignal = QtWidgets.QComboBox(self.frame_11)
        self.combox_TriggerSignal.setMinimumSize(QtCore.QSize(135, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.combox_TriggerSignal.setFont(font)
        self.combox_TriggerSignal.setObjectName("combox_TriggerSignal")
        self.horizontalLayout_27.addWidget(self.combox_TriggerSignal)
        self.verticalLayout_24.addLayout(self.horizontalLayout_27)
        self.verticalLayout_22.addLayout(self.verticalLayout_24)
        self.verticalLayout_23.addLayout(self.verticalLayout_22)
        self.verticalLayout_21.addWidget(self.frame_11)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem13)
        self.verticalLayout_20.addWidget(self.frame_10)
        self.tabWidget.addTab(self.tab_Trigger, "")
        self.tab_Lighting = QtWidgets.QWidget()
        self.tab_Lighting.setObjectName("tab_Lighting")
        self.tabWidget.addTab(self.tab_Lighting, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.frame_9 = QtWidgets.QFrame(self.vert)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_19.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(20, 5, -1, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.btn_SetAdvanced = QtWidgets.QPushButton(self.frame_9)
        self.btn_SetAdvanced.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_SetAdvanced.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_SetAdvanced.setFont(font)
        self.btn_SetAdvanced.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.btn_SetAdvanced.setObjectName("btn_SetAdvanced")
        self.horizontalLayout_20.addWidget(self.btn_SetAdvanced)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem14)
        self.btn_Ok = QtWidgets.QPushButton(self.frame_9)
        self.btn_Ok.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Ok.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_Ok.setFont(font)
        self.btn_Ok.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.btn_Ok.setObjectName("btn_Ok")
        self.horizontalLayout_20.addWidget(self.btn_Ok)
        spacerItem15 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem15)
        self.btn_Cancel = QtWidgets.QPushButton(self.frame_9)
        self.btn_Cancel.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Cancel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_Cancel.setFont(font)
        self.btn_Cancel.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.horizontalLayout_20.addWidget(self.btn_Cancel)
        self.verticalLayout_18.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(25, -1, -1, -1)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_11 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("font: 9pt \"Ubuntu\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_21.addWidget(self.label_11)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem16)
        self.verticalLayout_18.addLayout(self.horizontalLayout_21)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.verticalLayout_8.addWidget(self.frame_9)
        self.frae = QtWidgets.QFrame(self.vert)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frae.sizePolicy().hasHeightForWidth())
        self.frae.setSizePolicy(sizePolicy)
        self.frae.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.frae.setObjectName("frae")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frae)
        self.horizontalLayout_7.setContentsMargins(2, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.frae)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem17)
        self.btn_Run = QtWidgets.QPushButton(self.frame_2)
        self.btn_Run.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_Run.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_Run.setFont(font)
        self.btn_Run.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"color: rgb(238, 238, 236);")
        self.btn_Run.setObjectName("btn_Run")
        self.horizontalLayout_17.addWidget(self.btn_Run)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem18)
        self.btn_Running = QtWidgets.QPushButton(self.frame_2)
        self.btn_Running.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_Running.setFont(font)
        self.btn_Running.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"color: rgb(238, 238, 236);")
        self.btn_Running.setObjectName("btn_Running")
        self.horizontalLayout_17.addWidget(self.btn_Running)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_7.addWidget(self.frame_2)
        self.verticalLayout_8.addWidget(self.frae)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2.addWidget(self.vert)

        self.retranslateUi(Class_CameraSetting)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Class_CameraSetting)

    def retranslateUi(self, Class_CameraSetting):
        _translate = QtCore.QCoreApplication.translate
        Class_CameraSetting.setWindowTitle(_translate("Class_CameraSetting", "Dialog"))
        self.lab_InforLine1.setText(_translate("Class_CameraSetting", "Camera Settings"))
        self.lab_InforLine2.setText(_translate("Class_CameraSetting", "Sets the condition such as model, image size, brightness, etc .."))
        self.lab_InforLine3.setText(_translate("Class_CameraSetting", "of the camera to use for capturing."))
        self.btn_LelfCommand.setText(_translate("Class_CameraSetting", "<-"))
        self.btn_RightCommand.setText(_translate("Class_CameraSetting", "->"))
        self.comBox_Current_Image.setItemText(0, _translate("Class_CameraSetting", "Current Image"))
        self.btn_Live.setText(_translate("Class_CameraSetting", "Live"))
        self.lab_TitleTableSetting.setText(_translate("Class_CameraSetting", "CAM 1 : Camera Settings"))
        self.label_2.setText(_translate("Class_CameraSetting", "Camera Settings"))
        self.btn_settingCameraExtend.setText(_translate("Class_CameraSetting", ">>"))
        self.label_3.setText(_translate("Class_CameraSetting", "Model"))
        self.btn_AutoDetecTypeCamera.setText(_translate("Class_CameraSetting", "Auto"))
        self.lab_InfoCamera.setText(_translate("Class_CameraSetting", "Information Camera"))
        self.label_5.setText(_translate("Class_CameraSetting", "Size"))
        self.label_6.setText(_translate("Class_CameraSetting", "Shutter Speed"))
        self.label_7.setText(_translate("Class_CameraSetting", "ms"))
        self.label_8.setText(_translate("Class_CameraSetting", "Sensitivity"))
        self.lab_ValueSensitivity.setText(_translate("Class_CameraSetting", "4.9"))
        self.label_10.setText(_translate("Class_CameraSetting", "HDR/Calibration Settings"))
        self.cbox_HDR.setText(_translate("Class_CameraSetting", "HDR"))
        self.btn_setHDR.setText(_translate("Class_CameraSetting", "SET"))
        self.cbox_Calibration.setText(_translate("Class_CameraSetting", "Calibration"))
        self.btn_setCalibration.setText(_translate("Class_CameraSetting", "SET"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Camera), _translate("Class_CameraSetting", "Camera"))
        self.label_12.setText(_translate("Class_CameraSetting", "Trigger Settings"))
        self.btn_settingTriggerExtend.setText(_translate("Class_CameraSetting", ">>"))
        self.label_13.setText(_translate("Class_CameraSetting", "Trigger Mode"))
        self.rbtn_TriggerModeExternal.setText(_translate("Class_CameraSetting", "External"))
        self.rbtn_TriggerModeInternal.setText(_translate("Class_CameraSetting", "Internal"))
        self.ledit_TimeTriggerModeInternal.setText(_translate("Class_CameraSetting", "1"))
        self.label_14.setText(_translate("Class_CameraSetting", "ms"))
        self.label_15.setText(_translate("Class_CameraSetting", "Trigger Signal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Trigger), _translate("Class_CameraSetting", "Trigger"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Lighting), _translate("Class_CameraSetting", "Lighting"))
        self.btn_SetAdvanced.setText(_translate("Class_CameraSetting", "Advanced"))
        self.btn_Ok.setText(_translate("Class_CameraSetting", "OK"))
        self.btn_Cancel.setText(_translate("Class_CameraSetting", "Cancel"))
        self.label_11.setText(_translate("Class_CameraSetting", "Set Advanced"))
        self.btn_Run.setText(_translate("Class_CameraSetting", "Run"))
        self.btn_Running.setText(_translate("Class_CameraSetting", "Running"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Class_CameraSetting = QtWidgets.QDialog()
    ui = Ui_Class_CameraSetting()
    ui.setupUi(Class_CameraSetting)
    Class_CameraSetting.show()
    sys.exit(app.exec_())

