from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Class_DlogReadData_1Dcode(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        #Dialog.move(1920-1252+60, 310)
        Dialog.move(1920 - 1236 + 400 + 60, 310)
        #Dialog.resize(1160, 700)
        Dialog.resize(820, 700)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(400, 650))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setStyleSheet("background-color: rgb(0, 58, 88);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 575, 680))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_7.setMinimumSize(QtCore.QSize(350, 650))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_14.addWidget(self.label_5)
        self.frame_5 = QtWidgets.QFrame(self.frame_7)
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(1, 20))
        self.label_2.setMaximumSize(QtCore.QSize(200, 20))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.ledit_StartDigit_ReadData_1D = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_StartDigit_ReadData_1D.sizePolicy().hasHeightForWidth())
        self.ledit_StartDigit_ReadData_1D.setSizePolicy(sizePolicy)
        self.ledit_StartDigit_ReadData_1D.setMinimumSize(QtCore.QSize(200, 20))
        self.ledit_StartDigit_ReadData_1D.setMaximumSize(QtCore.QSize(200, 20))
        self.ledit_StartDigit_ReadData_1D.setAlignment(QtCore.Qt.AlignCenter)
        self.ledit_StartDigit_ReadData_1D.setObjectName("ledit_StartDigit_ReadData_1D")
        self.horizontalLayout_3.addWidget(self.ledit_StartDigit_ReadData_1D)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.ledit_LengReadData_ReadData_1D = QtWidgets.QLineEdit(self.frame_5)
        self.ledit_LengReadData_ReadData_1D.setMinimumSize(QtCore.QSize(200, 20))
        self.ledit_LengReadData_ReadData_1D.setMaximumSize(QtCore.QSize(200, 20))
        self.ledit_LengReadData_ReadData_1D.setAlignment(QtCore.Qt.AlignCenter)
        self.ledit_LengReadData_ReadData_1D.setObjectName("ledit_LengReadData_ReadData_1D")
        self.horizontalLayout_4.addWidget(self.ledit_LengReadData_ReadData_1D)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_14.addWidget(self.frame_5)
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_14.addWidget(self.label_4)
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.cbox_SplitData_ReadData_1D = QtWidgets.QCheckBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_SplitData_ReadData_1D.sizePolicy().hasHeightForWidth())
        self.cbox_SplitData_ReadData_1D.setSizePolicy(sizePolicy)
        self.cbox_SplitData_ReadData_1D.setMinimumSize(QtCore.QSize(0, 20))
        self.cbox_SplitData_ReadData_1D.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cbox_SplitData_ReadData_1D.setObjectName("cbox_SplitData_ReadData_1D")
        self.horizontalLayout_10.addWidget(self.cbox_SplitData_ReadData_1D)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.btn_SplitSetting_ReadData_1D = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_SplitSetting_ReadData_1D.sizePolicy().hasHeightForWidth())
        self.btn_SplitSetting_ReadData_1D.setSizePolicy(sizePolicy)
        self.btn_SplitSetting_ReadData_1D.setMinimumSize(QtCore.QSize(200, 20))
        self.btn_SplitSetting_ReadData_1D.setMaximumSize(QtCore.QSize(200, 20))
        self.btn_SplitSetting_ReadData_1D.setObjectName("btn_SplitSetting_ReadData_1D")
        self.horizontalLayout_9.addWidget(self.btn_SplitSetting_ReadData_1D)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.cbox_OutFixLeng_ReadData_1D = QtWidgets.QCheckBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_OutFixLeng_ReadData_1D.sizePolicy().hasHeightForWidth())
        self.cbox_OutFixLeng_ReadData_1D.setSizePolicy(sizePolicy)
        self.cbox_OutFixLeng_ReadData_1D.setMinimumSize(QtCore.QSize(0, 20))
        self.cbox_OutFixLeng_ReadData_1D.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cbox_OutFixLeng_ReadData_1D.setObjectName("cbox_OutFixLeng_ReadData_1D")
        self.horizontalLayout_8.addWidget(self.cbox_OutFixLeng_ReadData_1D)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.ledit_FillingCharac_ReadData_1D = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_FillingCharac_ReadData_1D.sizePolicy().hasHeightForWidth())
        self.ledit_FillingCharac_ReadData_1D.setSizePolicy(sizePolicy)
        self.ledit_FillingCharac_ReadData_1D.setMinimumSize(QtCore.QSize(200, 20))
        self.ledit_FillingCharac_ReadData_1D.setMaximumSize(QtCore.QSize(200, 20))
        self.ledit_FillingCharac_ReadData_1D.setAlignment(QtCore.Qt.AlignCenter)
        self.ledit_FillingCharac_ReadData_1D.setObjectName("ledit_FillingCharac_ReadData_1D")
        self.horizontalLayout_7.addWidget(self.ledit_FillingCharac_ReadData_1D)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.cbox_CallTextError_ReadData_1D = QtWidgets.QCheckBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_CallTextError_ReadData_1D.sizePolicy().hasHeightForWidth())
        self.cbox_CallTextError_ReadData_1D.setSizePolicy(sizePolicy)
        self.cbox_CallTextError_ReadData_1D.setMinimumSize(QtCore.QSize(0, 20))
        self.cbox_CallTextError_ReadData_1D.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cbox_CallTextError_ReadData_1D.setObjectName("cbox_CallTextError_ReadData_1D")
        self.horizontalLayout_6.addWidget(self.cbox_CallTextError_ReadData_1D)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(80, 20))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        spacerItem11 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.ledit_callTextError_ReadData_1D = QtWidgets.QLineEdit(self.frame_4)
        self.ledit_callTextError_ReadData_1D.setMinimumSize(QtCore.QSize(200, 20))
        self.ledit_callTextError_ReadData_1D.setMaximumSize(QtCore.QSize(200, 20))
        self.ledit_callTextError_ReadData_1D.setAlignment(QtCore.Qt.AlignCenter)
        self.ledit_callTextError_ReadData_1D.setObjectName("ledit_callTextError_ReadData_1D")
        self.horizontalLayout_5.addWidget(self.ledit_callTextError_ReadData_1D)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_14.addWidget(self.frame_4)
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_14.addWidget(self.label_3)
        self.frame_3 = QtWidgets.QFrame(self.frame_7)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.cbox_OutSymbleIdentifier_ReadData_1D = QtWidgets.QCheckBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_OutSymbleIdentifier_ReadData_1D.sizePolicy().hasHeightForWidth())
        self.cbox_OutSymbleIdentifier_ReadData_1D.setSizePolicy(sizePolicy)
        self.cbox_OutSymbleIdentifier_ReadData_1D.setMinimumSize(QtCore.QSize(0, 20))
        self.cbox_OutSymbleIdentifier_ReadData_1D.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cbox_OutSymbleIdentifier_ReadData_1D.setObjectName("cbox_OutSymbleIdentifier_ReadData_1D")
        self.horizontalLayout_11.addWidget(self.cbox_OutSymbleIdentifier_ReadData_1D)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(40, 5, 40, 5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lab_OutSymbleIdentifier_ReadData_1D = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_OutSymbleIdentifier_ReadData_1D.sizePolicy().hasHeightForWidth())
        self.lab_OutSymbleIdentifier_ReadData_1D.setSizePolicy(sizePolicy)
        self.lab_OutSymbleIdentifier_ReadData_1D.setMinimumSize(QtCore.QSize(0, 20))
        self.lab_OutSymbleIdentifier_ReadData_1D.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lab_OutSymbleIdentifier_ReadData_1D.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.lab_OutSymbleIdentifier_ReadData_1D.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_OutSymbleIdentifier_ReadData_1D.setObjectName("lab_OutSymbleIdentifier_ReadData_1D")
        self.horizontalLayout_13.addWidget(self.lab_OutSymbleIdentifier_ReadData_1D)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_9.addWidget(self.frame_6)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_14.addWidget(self.frame_3)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem13)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.btn_Ok_DlogReadData_1D = QtWidgets.QPushButton(self.frame_2)
        self.btn_Ok_DlogReadData_1D.setObjectName("btn_Ok_DlogReadData_1D")
        self.horizontalLayout.addWidget(self.btn_Ok_DlogReadData_1D)
        self.btn_Cancel_DlogReadData_1D = QtWidgets.QPushButton(self.frame_2)
        self.btn_Cancel_DlogReadData_1D.setObjectName("btn_Cancel_DlogReadData_1D")
        self.horizontalLayout.addWidget(self.btn_Cancel_DlogReadData_1D)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_11.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "1D Code Reader > Details of Read Data Settings "))
        self.label_5.setText(_translate("Dialog", "Primary Settings"))
        self.label_2.setText(_translate("Dialog", "Start Digit"))
        self.ledit_StartDigit_ReadData_1D.setText(_translate("Dialog", "001"))
        self.label_6.setText(_translate("Dialog", "Read Data Length"))
        self.ledit_LengReadData_ReadData_1D.setText(_translate("Dialog", "100"))
        self.label_4.setText(_translate("Dialog", "Options"))
        self.cbox_SplitData_ReadData_1D.setText(_translate("Dialog", "Split Data"))
        self.btn_SplitSetting_ReadData_1D.setText(_translate("Dialog", "Split Setting"))
        self.cbox_OutFixLeng_ReadData_1D.setText(_translate("Dialog", "Output Fixed Length"))
        self.label_7.setText(_translate("Dialog", "Filling Character ( 1 byte)"))
        self.cbox_CallTextError_ReadData_1D.setText(_translate("Dialog", "Call Text at Read Error"))
        self.label_8.setText(_translate("Dialog", "Text Called"))
        self.label_3.setText(_translate("Dialog", "Action to Protocols"))
        self.cbox_OutSymbleIdentifier_ReadData_1D.setText(_translate("Dialog", "Output Symbol Identifier"))
        self.lab_OutSymbleIdentifier_ReadData_1D.setText(_translate("Dialog", "UNIE"))
        self.btn_Ok_DlogReadData_1D.setText(_translate("Dialog", "OK"))
        self.btn_Cancel_DlogReadData_1D.setText(_translate("Dialog", "Cancel"))
